adeira/universe

.flowconfig, .yarn/cache/flow-bin-0.110.1.tgz, .yarn/cache/flow-bin-0.111.0.tgz, package.json, src/eslint-config-kiwicom/getCommonConfig.js, src/example-relay/package.json, src/fetch/src/fetchWithRetries.js, src/graphql-global-id/src/GlobalID.js, src/relay/package.json, src/relay/src/fetchers/createNetworkFetcher.js, src/vault2env/src/getParameters.js, yarn.lock
See: https://github.com/facebook/flow/releases/tag/v0.111.0
=> Dependencies: use Flow version 0.111.0

scripts/publishNPMPackages.js, src/docs/docs/oss/npm-packages.md, src/graphql-bc-checker/package.json, src/graphql-bc-checker/src/index.js, src/monorepo-utils/src/findRelatedWorkspaces.js, src/relay/bin/fetch-schema.js, src/relay/package.json, src/relay/src/compiler/getSchemaSource.js, src/signed-source/README.md, src/signed-source/package.json
=> Rename signed-source to @adeira/signed-source

.github/workflows/nodejs.yml
=> Activate scanner on CI

.github/workflows/nodejs.yml, .github/workflows/npm-publisher.yml, scripts/publishNPMPackages.js
Closes: https://github.com/adeira/universe/issues/11
=> CI: add action for NPM publisher

scripts/publishNPMPackages.js, src/relay/package.json
=> Release @adeira/relay 0.1.0

scripts/publishNPMPackages.js, src/babel-preset-adeira/package.json, src/test-utils/package.json
(failure: https://zeit.co/adeira/relay-example/olktcdd2i)
=> NPM: publish Relay Example dependencies

.github/workflows/continuous-integration.yml, .github/workflows/shipit.yml, src/monorepo-shipit/config/__tests__/example-relay.test.js, src/monorepo-shipit/config/example-relay.js
Closes: https://github.com/adeira/universe/issues/16
=> CI: setup Shipit

src/example-relay/package.json, src/example-relay/schema.graphql, src/relay/bin/fetch-schema.js
Closes: https://github.com/adeira/universe/issues/146
=> Relay: validate fetch bin required inputs

README.md
Closes: https://github.com/adeira/universe/issues/102
=> Docs: add adeira.dev link to README

src/example-relay/package.json, src/relay/package.json, src/relay/src/compiler/buildLanguagePlugin.js
So it doesn't bother users not using it.
=> Relay: load TS language plugin conditionally

src/relay/src/__tests__/RelayLogger.node.test.js, src/relay/src/__tests__/RelayLogger.test.js
Test that logger does not log in node
=> relay: Test that logger logs in browser

CONTRIBUTING.md
Closes https://github.com/adeira/universe/issues/120
=> docs: Update contrib guide on how to report issues

src/monorepo-scanner/src/scans/MainFields.scan.js
=> scanner: Add test to check if main fields file exists

src/example-relay/package.json, src/relay-utils/package.json
=> Release @adeira/relay-utils 0.2.0

src/example-relay/__github__/.github/workflows/continuous-integration.yml, src/monorepo-shipit/README.md, src/monorepo-shipit/config/__tests__/example-relay.test.js, src/monorepo-shipit/config/example-relay.js
Related to this MR: https://github.com/adeira/relay-example/pull/6
=> Relay example: Add CI configuration to run unit tests & flow

src/relay/src/__tests__/RelayLogger.test.js
based on discussion raised here: https://github.com/adeira/universe/pull/264
=> relay: Check console output of logger

src/relay-runtime/index.d.ts
This is just tiny fix of type, not solution for https://github.com/adeira/universe/issues/320
=> relay-runtime: Remove unnecessary flow annotation from TS file

src/eslint-config-adeira/__tests__/__snapshots__/index.test.js.snap, src/eslint-config-adeira/ourRules.js, src/eslint-plugin-adeira/README.md, src/eslint-plugin-adeira/src/index.js, src/eslint-plugin-adeira/src/rules/EslintRule.flow.js, src/eslint-plugin-adeira/src/rules/__tests__/graphql-require-description.test.js, src/eslint-plugin-adeira/src/rules/graphql-require-description.js
related to https://github.com/adeira/universe/issues/210
=> eslint-plugin: Add new "graphql-require-description" rule

flow-typed/npm/next_v9.x.x.js, src/example-relay/__github__/flow-typed/npm/next_v9.x.x.js, src/example-relay/src/pages/_document.js
see https://github.com/flow-typed/flow-typed/pull/3699
=> Upgrade flow definitions for next.js

package.json, src/example-relay/package.json, src/graphql-resolve-wrapper/src/index.js, yarn.lock
See: https://github.com/facebook/flow/releases/tag/v0.117.0
=> Flow. use version 0.117.0

src/__flowtests__/lints/unsafe-addition.js
=> Add flowtest for unsafe addition

src/example-relay/package.json, src/example-relay/src/graphql/Schema.js, src/example-relay/src/graphql/datasets/locations.json, src/example-relay/src/graphql/queries/Locations.js, src/example-relay/src/graphql/types/Location.js, src/example-relay/src/graphql/types/LocationArea.js, src/example-relay/src/graphql/types/LocationConnection.js, src/example-relay/src/pages/api/graphql.js, yarn.lock
This should already be enough to run all location examples.
We need to also add the currency to cover the polling example.
When all is developed, we can just flip the fetch function
to target this graphql server
=> Use next api to set up graphql server

src/example-relay/src/graphql/queries/Locations.js
Current implementation in graphql-js is broken.
This the the solution we used in graphql.kiwi.com to patch it
closes #406
=> Use own implementation of connectionFromArray

src/example-relay/package.json, src/relay-runtime/package.json, src/relay-utils/package.json, src/relay/package.json, src/relay/src/hooks/useRelayEnvironment.js, yarn.lock
Closes: https://github.com/adeira/universe/issues/421
=> Upgrade relay

.dockerignore
We don't have any docker files in the repo
=> Delete .dockerignore file

src/relay/package.json, src/relay/src/compiler/buildLanguagePlugin.js, src/relay/src/compiler/index.js, yarn.lock
We never ended up using it and I think it was a bad idea anyway. This reverts commit 70aaf335
Closes: https://github.com/adeira/universe/pull/427
=> Revert "Relay: expose language plugins interface"

src/monorepo-utils/src/getWorkspaceDependencies.js
fixes https://github.com/adeira/universe/issues/436
=> monorepo-utils: sanitize shell output of "yarn workspaces info"

src/babel-preset-adeira/package.json, src/eslint-runner/package.json, src/example-relay/package.json, src/flow-bin/package.json, src/monorepo-builder/package.json, src/monorepo-npm-publisher/package.json, src/monorepo-scanner/package.json, src/monorepo-shipit/package.json, src/monorepo-utils/package.json, src/relay/package.json
=> Release @adeira/monorepo-utils 0.4.0

src/example-relay/schema.graphql, src/example-relay/src/graphql/RootMutation.js, src/example-relay/src/graphql/Schema.js, src/example-relay/src/graphql/locations/locations.js, src/example-relay/src/graphql/locations/mutations/AddLocation.js, src/example-relay/src/graphql/locations/mutations/__tests__/__fixtures__/addLocation.graphql, src/example-relay/src/graphql/locations/mutations/__tests__/__fixtures__/addLocationError.graphql, src/example-relay/src/graphql/locations/mutations/__tests__/__snapshots__/mutation.test.js.snap, src/example-relay/src/graphql/locations/mutations/__tests__/mutation.test.js, src/example-relay/src/graphql/locations/types/input/AddLocationInput.js, src/example-relay/src/graphql/locations/types/output/AddLocationError.js, src/example-relay/src/graphql/locations/types/output/AddLocationOrError.js, src/example-relay/src/graphql/locations/types/output/AddLocationResponse.js, src/example-relay/src/graphql/locations/types/output/Location.js, src/example-relay/src/graphql/locations/types/output/LocationConnection.js, src/example-relay/src/graphql/types/Error.js
- Add RootMutation to schema
- Add Error interace type
- Create teh addLocationMutation in graphql
=> relay-example: Add location mutation

src/example-relay/package.json, src/relay-utils/package.json, src/relay/CHANGELOG.md, src/relay/package.json, src/relay/src/index.js
Release new version of packages depending on this change.
=> Expose use mutation from @adeira/relay root

src/relay/package.json, src/relay/src/hooks/useIsMountedRef.js, src/relay/src/hooks/useMutation.js
This is essentially the Relay internal implementation.
=> Sync Relay `useMutation` with Pipedrive repository

src/example-relay/package.json, src/relay-runtime/index.js, src/relay-runtime/package.json, src/relay-runtime/src/RelayRuntimeTypes.js, src/relay-utils/package.json, src/relay/CHANGELOG.md, src/relay/package.json, src/relay/src/runtimeTypes.flow.js
Using connection handler gave flow error because of mismatch in Record proxy type
=> Move Record proxy type from relay to relay-runtime

src/example-relay/next.config.js
=> Relay-example: use js-esm as build target

flow-typed/npm/react-dom_v16.x.x.js, package.json, src/example-relay/package.json, yarn.lock
See: https://github.com/facebook/flow/releases/tag/v0.122.0
=> Use Flow 0.122.0

src/relay-runtime/index.js, src/relay/src/__flowtests__/createEnvironment.js, src/relay/src/createEnvironment.js, src/relay/src/createRequestHandler.js
- Fix createEnvironment flow types
=> relay: Fix createRequestHandler flow types

src/graphql-relay/.npmignore, src/graphql-relay/LICENSE, src/graphql-relay/README.md, src/graphql-relay/package.json, src/graphql-relay/src/__tests__/starWarsConnection.test.js, src/graphql-relay/src/__tests__/starWarsMutation.test.js, src/graphql-relay/src/__tests__/starWarsObjectIdentification.test.js, src/graphql-relay/src/connection/__tests__/arrayconnection.test.js, src/graphql-relay/src/connection/__tests__/connection.test.js, src/graphql-relay/src/connection/arrayconnection.js, src/graphql-relay/src/connection/connection.js, src/graphql-relay/src/connection/connectiontypes.js, src/graphql-relay/src/index.js, src/graphql-relay/src/mutation/__tests__/mutation.test.js, src/graphql-relay/src/mutation/mutation.js, src/graphql-relay/src/node/__tests__/global.test.js, src/graphql-relay/src/node/__tests__/node.test.js, src/graphql-relay/src/node/__tests__/nodeasync.test.js, src/graphql-relay/src/node/__tests__/plural.test.js, src/graphql-relay/src/node/node.js, src/graphql-relay/src/node/plural.js, src/graphql-relay/src/test-helpers/starWarsData.js, src/graphql-relay/src/test-helpers/starWarsSchema.js, src/graphql-relay/src/utils/__tests__/base64.test.js, src/graphql-relay/src/utils/base64.js
This is a fork from graphql/graphql-relay-js.
We chose to for this, since PR's are no longer
being merged and no release has been done since
Jan 2019
=> Add @adeira/graphql-relay

scripts/publishedPackages.json, src/example-relay/package.json, src/example-relay/src/graphql/locations/queries/Locations.js, src/example-relay/src/graphql/locations/types/output/LocationConnection.js, src/example-relay/src/graphql/services/__tests__/connectionFromArray.test.js, src/example-relay/src/graphql/services/connectionFromArray.js, src/graphql-relay/package.json, yarn.lock
- Release `@adeira/graphql-relay@0.1.0`
=> Use adeira graphql relay in example-relay

src/babel-preset-adeira/package.json, src/eslint-runner/package.json, src/example-relay/package.json, src/flow-bin/package.json, src/monorepo-builder/package.json, src/monorepo-npm-publisher/package.json, src/monorepo-scanner/package.json, src/monorepo-shipit/package.json, src/monorepo-utils/package.json, src/monorepo-utils/src/glob.js, src/relay/package.json
Release @adeira/monorepo-utils 0.8.0
=> Improve glob options flow type

src/example-relay/__github__/.flowconfig
This makes it similar to our configuration in Universe.
=> Relay example: fix flowconfig

src/monorepo-shipit/config/__tests__/monorepo-shipit.test.js, src/monorepo-shipit/config/monorepo-shipit.js
See: https://github.com/adeira/shipit
=> Shipit: add setup for `monorepo-shipit`

package.json, src/eslint-config-adeira/CHANGELOG.md, src/eslint-config-adeira/__tests__/__snapshots__/index.test.js.snap, src/eslint-config-adeira/ourRules.js, src/eslint-config-adeira/package.json, src/relay/src/__flowtests__/CustomQueryRenderer.js, src/relay/src/__flowtests__/createPaginationContainer-missingProps.js, src/relay/src/__flowtests__/createPaginationContainer.js, src/relay/src/__flowtests__/createRefetchContainer-missingProps.js, src/relay/src/__flowtests__/createRefetchContainer.js, yarn.lock
Release `@adeira/eslint-config 3.1.0`
=> Upgrade eslint relay to 1.8.1

src/fetch/README.md
This is an alternative to mocking the fetch function
=> Add note about msw to readme

package.json, src/babel-preset-adeira/CHANGELOG.md, src/babel-preset-adeira/README.md, src/docs/README.md, src/eslint-plugin-adeira/README.md, src/eslint-plugin-graphql-fragments/README.md, src/example-relay/README.md, src/fetch/README.md, src/graphql-relay/README.md, src/graphql-resolve-wrapper/README.md, src/js/CHANGELOG.md, src/js/README.md, src/monorepo-npm-publisher/README.md, src/monorepo-utils/README.md, src/relay-utils/README.md, src/relay/README.md
Currently, we are checking only JS files via Eslint. This change adds additional check to markdown files as well.
=> Apply Prettier to markdown files

src/fetch/README.md, src/relay/CHANGELOG.md, src/relay/package.json, src/relay/src/createRequestHandler.js, src/relay/src/fetchers/createNetworkFetcher.js, yarn.lock
Test plan: start Relay Example, slow down your network request and click furiously - the identical network requests should be cancelled (best visible in bi-directional pagination example).
=> Fetch: implement Abort Controller (cancellable fetch)

package.json, src/eslint-plugin-graphql-fragments/package.json, src/example-relay/package.json, src/example-relay/schema.graphql, src/graphql-bc-checker/package.json, yarn.lock
Only @types/graphql-upload depended on graphql 14.
closes #821
=> Upgrade graphql to 15.x

src/eslint-config-adeira/CHANGELOG.md, src/eslint-plugin-adeira/src/rules/__tests__/no-invalid-flow-annotations.test.js, src/eslint-plugin-adeira/src/rules/no-invalid-flow-annotations.js
=> Eslint-config: Check valid flow modes

src/graphql-relay-fauna/README.md, src/graphql-relay-fauna/package.json, src/graphql-relay-fauna/src/__tests__/GlobalFaunaID.test.js, src/graphql-relay-fauna/src/__tests__/GlobalID.test.js, src/graphql-relay-fauna/src/index.js
Encode and decode fuctions exported
=> GraphQL Relay Fauna: Global ID helpers

src/relay/src/hooks/__flowtests__/useMutation.js, src/relay/src/hooks/useMutation.js, src/relay/src/mutations.js
See: https://github.com/facebook/relay/commit/96d9703761e222a740cbefbed567e6cfe8015e69
=> Relay: add missing `onUnsubscribe` into mutation config

.github/.mergify.yml
Seems like I broke it but I didn't like it anyway. I will keep looking for some better solution which is more open and more Github Actions friendly.
=> Remove Mergify

src/example-relay/package.json, src/sx/README.md, src/sx/package.json, src/sx/src/__tests__/renderStatic.test.js, src/sx/src/create.js
- Support pseudo classes in media queries
=> sx: Refactor create function

flow-typed/npm/next_v9.x.x.js, src/example-relay/package.json, src/example-relay/src/components/Navbar.js, src/example-relay/src/pages/api/graphql.js, yarn.lock
- Add cors to graphql endpoint
- Close open navbar when navigating
=> Example relay fixes

.github/workflows/continuous-integration.yml, .github/workflows/merge-pal.yml
This should help us to merge the PRs seamlessly. Just a test to see if it works well.
See: https://github.com/marketplace/actions/merge-pal
=> Add merge-pal Github action

src/example-relay/package.json, src/sx/__flowtests__/sx.js, src/sx/package.json, src/sx/src/__tests__/create.test.js, src/sx/src/create.js
Closes https://github.com/adeira/universe/issues/1007
=> SX: allow conditional styles

src/example-relay/package.json, src/example-relay/src/Homepage/locations/LocationsPaginatedBidirectional.js, src/example-relay/src/SSRLocations/LocationsQuery.js, src/example-relay/src/components/Navbar.js, src/example-relay/src/components/Select.js, src/example-relay/src/mutations/FadeIn.css, src/example-relay/src/mutations/FadeIn.js, src/example-relay/src/pages/_document.js, src/example-relay/src/styles/app.css, yarn.lock
- Remove styled-components from example relay
=> Replace grommet-icons with react-icons

src/sx/README.md, src/sx/src/StyleCollector.js, src/sx/src/__tests__/StyleCollector.test.js, src/sx/src/__tests__/__snapshots__/renderPageWithSX.test.js.snap, src/sx/src/__tests__/fixtures/@supports-nested.json, src/sx/src/__tests__/fixtures/@supports.json, src/sx/src/__tests__/fixtures/@unknown.error.json, src/sx/src/__tests__/fixtures/media-queries-nested-deep.json
It behaves very similar to `@media` (indefinitely nested conditional rule) so allowing such rule is trivial.
=> SX: allow '@supports' at rule

package.json, src/eslint-config-adeira/package.json, src/eslint-runner/package.json, src/eslint-runner/src/__tests__/__snapshots__/codeframe.test.js.snap, src/eslint-runner/src/__tests__/codeframe.test.js, src/eslint-runner/src/__tests__/sleepSort.js, src/eslint-runner/src/codeframe.js
Closes https://github.com/adeira/universe/issues/1062
=> Eslint runner: print warnings first

src/sx/package.json, src/sx/src/__tests__/__snapshots__/renderPageWithSX.test.js.snap, src/sx/src/css-renderers/__tests__/renderAtomicClass.test.js, src/sx/src/css-renderers/renderAtomicClass.js, src/sx/src/renderPageWithSX.js
Class selector inside media query is repeated twice to increase the specificity.
https://styled-components.com/docs/advanced#issues-with-specificity
=> SX: Bump up specificity inside media query

src/sx-tailwind/.npmignore, src/sx-tailwind/.storybook/.babelrc.js, src/sx-tailwind/.storybook/main.js, src/sx-tailwind/.storybook/preview-head.html, src/sx-tailwind/.storybook/preview.js, src/sx-tailwind/README.md, src/sx-tailwind/package.json, src/sx-tailwind/src/storybook/buttons.stories.js, yarn.lock
=> SX Tailwind: Storybook

.jest.config.js, src/sx/jest.config.js, src/sx/package.json, src/sx/scripts/setupTests.js, src/sx/src/__tests__/SxDomTests.test.js, yarn.lock
This way we can assert on actually applied style instead of just
checking the class name
=> sx: Add some tests with testing-library

src/sx/package.json, src/sx/src/StyleCollector.js, src/sx/src/__tests__/StyleCollector.test.js, src/sx/src/__tests__/__snapshots__/renderPageWithSX.test.js.snap, src/sx/src/__tests__/fixtures/media-queries-same-style.json
Same styles inside and outside of media queries don't have the same hash anymore.
Closes #1090
=> SX: Style hashes inside media queries fix

WORKSPACE.bazel, src/flow-bin/BUILD.bazel, src/graphql-global-id/BUILD.bazel, src/graphql-relay-fauna/BUILD.bazel, src/graphql-relay/BUILD.bazel, src/graphql-result-size/BUILD.bazel, src/monorepo-npm-publisher/BUILD.bazel, src/monorepo-scanner/BUILD.bazel, src/monorepo-shipit/BUILD.bazel, src/relay-runtime/BUILD.bazel, src/relay-utils/BUILD.bazel, src/sx-tailwind/BUILD.bazel
See: https://github.com/adeira/universe/pull/1068
=> Bazel: offload more BUILD files

src/babel-preset-adeira/package.json, src/example-relay/package.json, src/graphql-bc-checker/package.json, src/graphql-result-size/package.json, src/monorepo-npm-publisher/package.json, src/monorepo-scanner/package.json, src/monorepo-shipit/package.json, src/sx/package.json, src/test-utils/package.json
Mostly internal changes and dependency upgrades.
=> Release '@adeira/test-utils' version 0.6.0

src/sx-tailwind/index.js, src/sx-tailwind/package.json
Style definitions will be needed for Babel plugin
=> SX Tailwind: Export style definitions

src/eslint-config-adeira/CHANGELOG.md, src/eslint-config-adeira/__tests__/__snapshots__/index.test.js.snap, src/eslint-config-adeira/ourRules.js, src/relay/src/LocalQueryRenderer.js, src/relay/src/QueryRenderer.js
It seems like it is finally working
=> eslint-config: Turn on flowtype/require-readonly-react-props

.github/FUNDING.yml
This reverts commit 85afc2c77fc5d4bc024333d69a3bfaff734158f3.
=> Revert "Add tbergq to FUNDING.yml"

src/example-relay/package.json, src/example-relay/src/Homepage/locations/LocationsList.js, src/example-relay/src/Homepage/locations/LocationsPaginated.js, src/example-relay/src/Homepage/locations/LocationsPaginatedBidirectional.js, src/example-relay/src/Homepage/locations/LocationsPaginatedRefetch.js, src/example-relay/src/components/Heading.js, src/example-relay/src/mutations/LocationsList.js, src/example-relay/src/mutations/RangeAdd/LocationsForm.js, src/example-relay/src/pages/_document.js, src/sx-tailwind/package.json, src/sx/README.md, src/sx/package.json, src/sx/src/__tests__/SxDomTests.test.js, src/sx/src/renderPageWithSX.js
- Release a new version of sx
- Use sx reset in example relay. 
As suggested in #996
=> sx: Include simple css reset

src/example-relay/package.json, src/example-relay/src/createRelayEnvironment.js
New domain: https://relay-example.adeira.dev/
=> Relay example: update domain

src/monorepo-shipit/src/RepoGit.js
This should help us debug what's going on when Shipit fails during patch apply.
=> Shipit: show current failed patch

src/monorepo-shipit/README.md
Freshen it up with hopefully better copy, better explanations and without some historical relics (our previous private GitLab repo).
=> Shipit: update docs

src/sx-tailwind-website/src/components/Sidebar.js
This should be a temporary fix until support for runtime styles is done in SX
=> SXT Website: Don't use Next.js Link

vercel.json
See https://vercel.com/knowledge/how-to-prevent-vercel-github-comments
=> Turn off Vercel integration comments

src/monorepo-shipit/config/__tests__/js.test.js, src/monorepo-shipit/config/js.js
=> Shipit: configure '@adeira/js' export

src/example-relay/package.json, src/monorepo-npm-publisher/src/transformFileVariants.js, src/sx-tailwind-website/package.json, src/sx-tailwind/package.json, src/sx/package.json
- Set reactRuntime: 'automatic' in npm-monorepo-publisher
=> Release @adeira/sx 0.17.0

src/sx/README.md, src/sx/src/__tests__/__snapshots__/fixtures.test.js.snap, src/sx/src/__tests__/fixtures/readme-example.js, src/sx/src/__tests__/fixtures/variables.js, src/sx/src/transformStyleName.js
Just additional tests to make sure it works correctly. I also updated the README to showcase we support CSS variables.
=> SX: add CSS variables declaration fixture

babel.config.js, package.json, src/babel-preset-adeira/CHANGELOG.md, src/babel-preset-adeira/README.md, src/babel-preset-adeira/package.json, src/babel-preset-adeira/src/__tests__/__snapshots__/transformations.test.js.snap, src/babel-preset-adeira/src/index.js, src/example-relay/.babelrc.js, src/example-relay/__github__/babel.config.js, src/example-relay/package.json, src/monorepo-npm-publisher/CHANGELOG.md, src/monorepo-npm-publisher/README.md, src/monorepo-npm-publisher/package.json, src/monorepo-npm-publisher/src/index.js, src/monorepo-npm-publisher/src/transformFileVariants.js, src/sx-tailwind-website/.babelrc.js, src/sx-tailwind-website/__github__/babel.config.js, src/sx-tailwind-website/package.json, src/sx-tailwind/package.json
closes #1253
Release @adeira/babel-preset-adeira 2.0.0
=> babel-preset: Set reactRuntime automatic as default

src/sx/README.md
Better explain how should the `sx()` function be used with multiple classes (to prevent manual className casting).
=> SX: update docs

src/example-relay/package.json, src/sx-tailwind-website/package.json, src/sx-tailwind/package.json, src/sx/package.json
This version includes runtime styles support.
=> Release @adeira/sx version 0.18.0

src/example-relay/src/components/Navbar.js
The navbar was not being closed on click on mobile. This commit should fix it.
=> Relay example: fix navbar 'onClick' handler

src/babel-plugin-transform-sx-tailwind/package.json, src/babel-plugin-transform-sx-tailwind/src/__tests__/fixtures/custom-font/code.js, src/babel-plugin-transform-sx-tailwind/src/__tests__/fixtures/custom-font/options.json, src/babel-plugin-transform-sx-tailwind/src/__tests__/fixtures/custom-font/output.js, src/babel-plugin-transform-sx-tailwind/src/getCssDeclarations.js, src/babel-plugin-transform-sx-tailwind/src/index.js, src/sx-tailwind-website/.babelrc.js, src/sx-tailwind-website/__github__/babel.config.js, src/sx-tailwind-website/package.json, src/sx-tailwind-website/src/components/Layout.js, src/sx-tailwind-website/src/pages/_document.js, yarn.lock
Just a first step toward a full `tailwind.config.js` support:
https://tailwindcss.com/docs/configuration#theme
=> SXT Babel: Support for custom font family

src/example-relay/package.json, src/sx-tailwind-website/package.json, src/sx-tailwind/package.json, src/sx/README.md, src/sx/__flowtests__/css-properties.js, src/sx/index.js, src/sx/package.json, src/sx/src/StyleCollector.js, src/sx/src/__tests__/StyleCollector.test.js, src/sx/src/__tests__/SxDomTests.test.js, src/sx/src/__tests__/__snapshots__/fixtures.test.js.snap, src/sx/src/__tests__/fixtures/keyframes-from-to.js, src/sx/src/__tests__/fixtures/keyframes-percentage.js, src/sx/src/__tests__/keyframes.test.js, src/sx/src/create.js, src/sx/src/injectRuntimeStyles.js, src/sx/src/keyframes.js, yarn.lock
=> sx: Add keyframes support

src/sx/src/__tests__/injectRuntimeStyles.test.js, src/sx/src/injectRuntimeStyles.js
This was defined outside the loop before, it was ok but confusing.
It is easy to think that this works like an array and that you are
overwriting index, though it is just adding and pushing the other down.
Also added a test for that the runtime styles are added correctly
=> sx: Calculate insertIndex inside loop in injectRuntimeStyles

src/sx/src/__tests__/expandShorthandProperties.test.js, src/sx/src/expandShorthandProperties.js
See: https://developer.mozilla.org/en-US/docs/Web/CSS/flex
Please, pay extra attention to details to make sure it's expanded according to MDN.
=> SX: expand shorthand 'flex' property

.github/workflows/continuous-integration.yml, .github/workflows/npm-publisher.yml, .github/workflows/shipit.yml, src/example-relay/__github__/.github/workflows/continuous-integration.yml, src/sx-tailwind-website/__github__/.github/workflows/continuous-integration.yml
Node 12 is no longer lts version, it is now Node 14 that is lts
=> Remove node 12.x from node-version matrix

src/adeira.dev/static/css/custom.css
Add adeira-primary-color CSS variable and use it in homeContainer
=> adeira.dev: Use same text color in homeContainer as rest of application

.github/workflows/continuous-integration.yml, .github/workflows/npm-publisher.yml, .github/workflows/shipit.yml, src/example-relay/__github__/.github/workflows/continuous-integration.yml, src/sx-tailwind-website/__github__/.github/workflows/continuous-integration.yml
This reverts commit e03a9813f41479ff770937d05fdd6df9e279cad7.
=> Revert "Remove node 12.x from node-version matrix"

.github/.kodiak.toml
This enables Kodiak automation to merge PR with label "automerge"
=> Use Kodiak automation

src/sx-tailwind-website/__github__/babel.config.js, src/sx-tailwind-website/package.json, yarn.lock
Issues in exported repo are visible after the export :-(
=> SXT Website: Fix babel config and deps

src/sx-tailwind-website/package.json
Hopefully the last fix for exported repository
=> SXT Website: PostCSS as a dependency

src/ya-comiste-react-native/ios/Podfile.lock, src/ya-comiste-react-native/package.json, yarn.lock
See: https://github.com/facebook/react-native/releases/tag/v0.63.4
=> Dependencies: use React Native 0.63.4

src/eslint-config-adeira/CHANGELOG.md, src/eslint-config-adeira/__tests__/__snapshots__/index.test.js.snap, src/eslint-config-adeira/ourRules.js, src/eslint-plugin-adeira/package.json, src/eslint-plugin-adeira/src/rules/__tests__/fixtures/no-unmasked-graphql-id-without-alias/.eslintrc.js, src/eslint-plugin-adeira/src/rules/__tests__/fixtures/no-unmasked-graphql-id-without-alias/invalid/missing-alias-deep.js, src/eslint-plugin-adeira/src/rules/__tests__/fixtures/no-unmasked-graphql-id-without-alias/invalid/missing-alias.js, src/eslint-plugin-adeira/src/rules/__tests__/fixtures/no-unmasked-graphql-id-without-alias/valid/aliased-id.js, src/eslint-plugin-adeira/src/rules/__tests__/fixtures/no-unmasked-graphql-id-without-alias/valid/opaque-id.js, src/eslint-plugin-adeira/src/rules/__tests__/fixtures/no-unmasked-graphql-id-without-alias/valid/unrelated-fields.js, src/eslint-plugin-adeira/src/rules/__tests__/no-unmasked-graphql-id-without-alias.test.js, src/eslint-plugin-adeira/src/rules/no-unmasked-graphql-id-without-alias.js, src/flow-types-eslint/src/index.js, src/graphql-global-id/README.md, src/relay/src/__flowtests__/createFragmentContainer.js
Closes: https://github.com/adeira/universe/issues/767
TODO:
=> Eslint: add safe guard for 'id(opaque:false)' without alias

src/monorepo-shipit/config/__tests__/css-colors.test.js, src/monorepo-shipit/config/css-colors.js
Destination: https://github.com/adeira/css-colors
=> Monorepo Shipit: setup 'adeira/css-colors'

src/monorepo-shipit/config/__tests__/fetch.test.js, src/monorepo-shipit/config/fetch.js
Destination: https://github.com/adeira/fetch
=> Monorepo Shipit: setup fetch

src/monorepo-shipit/config/__tests__/ya-comiste.test.js, src/monorepo-shipit/config/ya-comiste.js, src/monorepo-shipit/src/ShipitConfig.js
This is an experimental monorepo-to-monorepo setup. We never actually used it so I'd like to test it.
Destination: https://github.com/adeira/ya-comiste
=> Monorepo Shipit: setup 'ya-comiste' (experimental)

src/ya-comiste-rust/crates/sdui/src/model/scrollview_horizontal.rs, src/ya-comiste-rust/crates/sdui/src/sdui_scrollview_horizontal_component.rs
This fixes broken tests (the branch protection was not set correctly).
=> YCR: use connection pool for fetching scrollview cards

src/monorepo-shipit/bin/shipit.js, src/monorepo-shipit/src/Changeset.js, src/monorepo-shipit/src/RepoGit.js, src/monorepo-shipit/src/ShipitConfig.js, src/monorepo-shipit/src/__tests__/Changeset.test.js, src/monorepo-shipit/src/__tests__/__snapshots__/ShipitConfig.test.js.snap, src/monorepo-shipit/src/filters/__tests__/__snapshots__/moveDirectories.test.js.snap, src/monorepo-shipit/src/filters/__tests__/moveDirectoriesReverse.test.js, src/monorepo-shipit/src/filters/__tests__/stripDescriptions.test.js, src/monorepo-shipit/src/filters/__tests__/stripPaths.test.js, src/monorepo-shipit/src/filters/addTrackingData.js, src/monorepo-shipit/src/filters/conditionalLines.js, src/monorepo-shipit/src/filters/moveDirectories.js, src/monorepo-shipit/src/filters/moveDirectoriesReverse.js, src/monorepo-shipit/src/filters/stripDescriptions.js, src/monorepo-shipit/src/filters/stripExceptDirectories.js, src/monorepo-shipit/src/filters/stripPaths.js, src/monorepo-shipit/src/iterateConfigs.js, src/monorepo-shipit/src/parsePatchHeader.js, src/monorepo-shipit/src/phases/createCheckCorruptedRepoPhase.js, src/monorepo-shipit/src/phases/createCleanPhase.js, src/monorepo-shipit/src/phases/createClonePhase.js, src/monorepo-shipit/src/phases/createImportSyncPhase.js, src/monorepo-shipit/src/phases/createPushPhase.js, src/monorepo-shipit/src/phases/createSyncPhase.js, src/monorepo-shipit/src/phases/createVerifyRepoPhase.js, src/monorepo-shipit/src/utils/createMockChangeset.js
This commit hides console outputs from Git and instead displays custom messages for more understandable output about what's going on inside Shipit. Similar to how original FBShipit works: https://github.com/facebook/fbshipit/blob/a3c7cd8c97ef1b49c2b9c371b14b0051c3a7631b/DEBUGGING.md
=> Shipit: improve logging

src/relay-runtime/package.json, src/relay/package.json, yarn.lock
See: https://github.com/facebook/relay/releases/tag/v10.1.1
=> Use latest Relay version 10.1.1

src/monorepo-shipit/config/__tests__/ya-comiste.test.js, src/monorepo-shipit/config/ya-comiste.js, src/monorepo-shipit/src/ShipitConfig.js
Reverts adeira/universe#1468
Attempt number 2 😊
=> Revert "Revert "Monorepo Shipit: setup 'ya-comiste' (experimental)""

src/monorepo-shipit/bin/shipit.js, src/monorepo-shipit/package.json, src/monorepo-shipit/src/Changeset.js, src/monorepo-shipit/src/__tests__/Changeset.test.js, src/monorepo-shipit/src/__tests__/__snapshots__/ShipitConfig.test.js.snap, src/monorepo-shipit/src/__tests__/__snapshots__/parsePatchHeader.test.js.snap, src/monorepo-shipit/src/filters/__tests__/__snapshots__/moveDirectories.test.js.snap, src/monorepo-shipit/src/filters/__tests__/__snapshots__/stripPaths.test.js.snap, src/monorepo-shipit/src/filters/__tests__/addTrackingData.test.js, src/monorepo-shipit/src/filters/__tests__/stripPaths.test.js, src/monorepo-shipit/src/filters/addTrackingData.js, src/monorepo-shipit/src/filters/stripPaths.js, src/monorepo-shipit/src/iterateConfigs.js, src/monorepo-shipit/src/phases/createImportSyncPhase.js, src/monorepo-shipit/src/phases/createSyncPhase.js
Because I am a chimp who doesn't know how to use my own code.
=> Shipit: fix debug messages

.github/workflows/continuous-integration-rust.yml
This should reduce the repetition (the CI is the same for everything, just different targets for different machines).
=> Rust CI: use testing matrix

src/eslint-plugin-sx/package.json, src/example-relay/package.json, src/sx-tailwind-website/package.json, src/sx-tailwind-website/src/TailwindCss/Gradients.js, src/sx-tailwind-website/src/TailwindCss/gradients/TextBackground.js, src/sx-tailwind/package.json, src/sx/README.md, src/sx/package.json, src/sx/src/StyleCollector.js, src/sx/src/StyleCollectorAtNode.js, src/sx/src/StyleCollectorNode.js, src/sx/src/StyleCollectorNodeInterface.js, src/sx/src/__tests__/SxDomTests.test.js, src/sx/src/__tests__/__snapshots__/fixtures.test.js.snap, src/sx/src/__tests__/autoprefixRuntimeStyles.test.js, src/sx/src/__tests__/fixtures/autoprefix.js, src/sx/src/__tests__/injectRuntimeStyles.test.js, src/sx/src/injectRuntimeStyles.js, src/sx/src/renderPageWithSX.js, yarn.lock
Vendor prefixes are automatically added into the generated CSS.
=> SX: Automatic vendor prefixes

src/monorepo-shipit/config/__tests__/babel-preset-adeira.test.js, src/monorepo-shipit/config/babel-preset-adeira.js
Destination: https://github.com/adeira/babel-preset-adeira
=> Shipit: configure 'babel-preset-adeira'

src/ya-comiste-rust/arangodb/src/lib.rs, src/ya-comiste-rust/sdui/src/graphql_context.rs, src/ya-comiste-rust/sdui/src/graphql_schema.rs, src/ya-comiste-rust/sdui/src/lib.rs, src/ya-comiste-rust/sdui/src/model/component_content.rs, src/ya-comiste-rust/sdui/src/model/entrypoints.rs, src/ya-comiste-rust/sdui/src/model/scrollview_horizontal.rs, src/ya-comiste-rust/sdui/src/model/sdui_sections.rs, src/ya-comiste-rust/sdui/src/sdui_scrollview_horizontal_component.rs, src/ya-comiste-rust/sdui/src/sdui_section.rs, src/ya-comiste-rust/sdui/src/user.rs, src/ya-comiste-rust/server/src/main.rs
Unused at this moment. But I have to be able to work with the users somewhere down the road. This is a first step.
=> YCR: bootstrap anonymous and identified user

.github/workflows/continuous-integration-rust.yml
See: https://doc.rust-lang.org/book/ch11-02-running-tests.html#ignoring-some-tests-unless-specifically-requested
=> CI: run ignored Rust tests

src/monorepo-shipit/config/__tests__/relay.test.js, src/monorepo-shipit/config/relay.js
Destination: https://github.com/adeira/relay
=> Shipit: setup 'relay'

package.json, src/eslint-config-adeira/CHANGELOG.md, src/eslint-config-adeira/package.json
=> Eslint config: release version 4.3.0

src/eslint-config-adeira/CHANGELOG.md, src/eslint-config-adeira/__tests__/__snapshots__/index.test.js.snap, src/eslint-config-adeira/ourRules.js, src/sx-tailwind-website/src/components/sidebar/Context.js
=> Eslint config: enable 'react/jsx-no-constructed-context-values' rule

src/eslint-config-adeira/package.json, src/eslint-plugin-sx/package.json, src/eslint-plugin-sx/src/rules/__tests__/fixtures/no-unused-stylesheet/invalid/composability.js, src/eslint-plugin-sx/src/rules/__tests__/fixtures/no-unused-stylesheet/valid/composability-identifier-property.js, src/eslint-plugin-sx/src/rules/__tests__/fixtures/no-unused-stylesheet/valid/composability-literal-property.js, src/eslint-plugin-sx/src/rules/no-unused-stylesheet.js, src/flow-types-eslint/src/index.js, src/flow-types-eslint/src/types/JSXExpressionContainer.js, src/flow-types-eslint/src/types/MemberExpression.js, src/flow-types-eslint/src/types/TemplateLiteral.js
Closes: https://github.com/adeira/universe/issues/1585
=> SX eslint: improve unused composited styles detection

src/adeira.dev/package.json, src/babel-preset-adeira/package.json, src/example-relay/package.json, src/monorepo-npm-publisher/package.json, src/sx-tailwind-website/package.json, src/sx-tailwind/package.json
Mostly internal changes and dependency updates.
=> Release '@adeira/babel-preset-adeira' version 2.0.1

package.json, src/eslint-fixtures-tester/package.json, src/eslint-plugin-adeira/package.json, src/eslint-plugin-sx/package.json, yarn.lock
See: https://eslint.org/blog/2021/01/eslint-v7.18.0-released
=> Upgrade 'eslint' to the latest version 7.18.0

scripts/publishedPackages.json, src/sx-design/.npmignore, src/sx-design/LICENSE, src/sx-design/README.md, src/sx-design/index.js, src/sx-design/package.json, src/sx-design/src/.eslintrc.js, src/sx-design/src/Heading.js, src/sx-design/src/HeadingLevel.js, src/sx-design/src/ProductCard.js, src/sx-design/src/Section.js, src/sx-design/src/Skeleton.js, src/sx-design/src/SkipLink.js, src/sx-design/src/__tests__/Heading.test.js, src/sx-design/src/__tests__/__snapshots__/Heading.test.js.snap
The purpose of this package is to share common components written using SX (so it fits well with applications written is SX).
=> Open source new '@adeira/sx-design'

src/ya-comiste-rust/Cargo.lock, src/ya-comiste-rust/server/Cargo.toml
With views, analyzers and transactions.
=> YCR: use 'arangors' version 0.4.6

src/ya-comiste-rust/Cargo.lock, src/ya-comiste-rust/signedsource/Cargo.toml, src/ya-comiste-rust/signedsource/README.md, src/ya-comiste-rust/signedsource/RELEASING.md
https://crates.io/crates/signedsource
=> Rust signedsource: add README.md

src/monorepo-npm-publisher/CHANGELOG.md, src/monorepo-npm-publisher/src/NPM.js, src/monorepo-npm-publisher/src/index.js
=> NPM Publisher: Improved NPM API error handling

src/ya-comiste-rust/README.md, src/ya-comiste-rust/server/src/arangodb/mod.rs
The ultimate goal is to manage everything around the DB automatically.
=> YCR: create a new DB automatically in case it doesn't exist

src/monorepo-npm-publisher/src/NPM.js, src/monorepo-npm-publisher/src/index.js
I do not know what and when it went wrong. So I created a new "automation" token for the NPM Publisher and made some tweaks until it started working again.
Closes: https://github.com/adeira/universe/issues/1671
=> Improve NPM publisher logic

src/eslint-plugin-sx/src/rules/__tests__/__snapshots__/no-unused-stylesheet.test.js.snap, src/eslint-runner/src/__tests__/__snapshots__/codeframe.test.js.snap
Probably some of the latest Babel updates broke these snapshots silently.
=> Fix broken Babel Codeframe snapshots

src/babel-preset-adeira/CHANGELOG.md, src/css-colors/CHANGELOG.md, src/eslint-config-adeira/CHANGELOG.md, src/fetch/CHANGELOG.md, src/graphql-bc-checker/CHANGELOG.md, src/graphql-global-id/CHANGELOG.md, src/js/CHANGELOG.md, src/monorepo-npm-publisher/CHANGELOG.md, src/relay/CHANGELOG.md
=> Changelogs: add Node.js 12 deprecation notice

src/ya-comiste-rust/.dockerignore, src/ya-comiste-rust/Dockerfile, src/ya-comiste-rust/README.md
Inspiration: https://www.lpalmieri.com/posts/2020-11-01-zero-to-production-5-how-to-deploy-a-rust-application
=> YCR: add basic Dockerfile

src/css-colors/CHANGELOG.md, src/css-colors/package.json, src/sx/package.json
=> Release '@adeira/css-colors' version 2.0.0

scripts/package.json, src/graphql-bc-checker/package.json, src/relay/package.json, src/signed-source/CHANGELOG.md, src/signed-source/package.json, src/sx-tailwind/package.json, src/sx/package.json
=> Release '@adeira/signed-source' version 2.0.0

package.json, src/eslint-config-adeira/CHANGELOG.md, src/eslint-config-adeira/package.json
=> Release '@adeira/eslint-config' version 5.0.0

src/eslint-config-adeira/CHANGELOG.md, src/eslint-config-adeira/ourRules.js
It was missed here: https://github.com/adeira/universe/commit/43de79290d2ece4bb8e0db2da659dffb8f58c5a5
=> Eslint config: update changelog

src/example-relay/package.json, src/fetch/CHANGELOG.md, src/fetch/package.json, src/relay/package.json
=> Release '@adeira/fetch' version 2.0.0

package.json, src/adeira.dev/package.json, src/babel-preset-adeira/CHANGELOG.md, src/babel-preset-adeira/package.json, src/example-relay/package.json, src/monorepo-npm-publisher/package.json, src/sx-tailwind-website/package.json, src/sx-tailwind/package.json
=> Release '@adeira/babel-preset-adeira' version 3.0.0

scripts/package.json, src/css-colors/package.json, src/eslint-fixtures-tester/package.json, src/example-relay/package.json, src/fetch/package.json, src/fixtures-tester/package.json, src/flow-bin/package.json, src/flow-config-parser/package.json, src/graphql-global-id/package.json, src/graphql-relay-fauna/package.json, src/js/CHANGELOG.md, src/js/package.json, src/monorepo-scanner/package.json, src/monorepo-shipit/package.json, src/monorepo-utils/package.json, src/relay-runtime/package.json, src/relay/package.json, src/sx-tailwind/package.json, src/sx/package.json, src/ya-comiste-backoffice/package.json
=> Release '@adeira/js' version 2.0.0

src/example-relay/package.json, src/relay-utils/package.json, src/relay/CHANGELOG.md, src/relay/package.json, src/ya-comiste-backoffice/package.json
=> Release '@adeira/relay' version 3.0.0

.github/workflows/continuous-integration-javascript.yml, .github/workflows/npm-publisher.yml
Related issue: https://github.com/adeira/universe/issues/1718
=> CI: drop Node.js version 12

src/eslint-plugin-sx/src/rules/no-unused-stylesheet.js, src/eslint-plugin-sx/src/rules/valid-usage.js
Depends on: https://github.com/adeira/universe/pull/1750
=> Simplify 'eslint-plugin-sx' code

flow-typed/npm/yup_v0.x.x.js, src/ya-comiste-backoffice/package.json, src/ya-comiste-backoffice/pages/products/create.js, yarn.lock
@adeira/devs This PR also requires your input. Thank you! 😊
=> YCBO: use Yup validations

src/ya-comiste-meta/schema.graphql, src/ya-comiste-rust/server/src/commerce/api/mod.rs, src/ya-comiste-rust/server/src/commerce/dal/mod.rs, src/ya-comiste-rust/server/src/commerce/dal/products.rs, src/ya-comiste-rust/server/src/commerce/mod.rs, src/ya-comiste-rust/server/src/commerce/model/products.rs, src/ya-comiste-rust/server/src/graphql_schema.rs, src/ya-comiste-rust/server/src/migrations/v4__create_collection_products.rs
This way we can create the product in spanish, english, or both at the same time.
=> YCR: allow multilingual create product input

src/sx-design/package.json, src/sx-design/src/Money.js, src/sx-design/src/ProductCard.js, src/sx-design/src/constants.js, yarn.lock
=> SX design: offload 'ProductCard' design

src/monorepo-shipit/config/__tests__/sx-design.test.js, src/monorepo-shipit/config/sx-design.js
Destination: https://github.com/adeira/sx-design
=> Shipit: setup SX Design exports

src/ya-comiste-backoffice/.babelrc.js, src/ya-comiste-backoffice/pages/index.js, src/ya-comiste-backoffice/pages/products.js, src/ya-comiste-backoffice/pages/users.js, src/ya-comiste-backoffice/src/AuthButtons.js, src/ya-comiste-backoffice/src/Layout.js, src/ya-comiste-backoffice/src/Link.js, src/ya-comiste-backoffice/src/Navigation.js, src/ya-comiste-backoffice/translations/out/es_MX.json, src/ya-comiste-backoffice/translations/source_strings.json, src/ya-comiste-backoffice/translations/src_manifest.json
Just some simple styling, nothing complicated.
=> YCBO: update design

src/eslint-plugin-sx/package.json, src/example-relay/package.json, src/sx-design/package.json, src/sx-design/src/Heading.js, src/sx-design/src/Section.js, src/sx-tailwind-website/package.json, src/sx-tailwind/package.json, src/sx/README.md, src/sx/__flowtests__/composability.js, src/sx/__flowtests__/css-properties.js, src/sx/__flowtests__/sx.js, src/sx/index.js, src/sx/package.json, src/sx/src/__tests__/composability.test.js, src/sx/src/create.js, src/ya-comiste-backoffice/package.json, src/ya-comiste-backoffice/src/Link.js
Closes: https://github.com/adeira/universe/issues/1584
=> SX: fix Flow types when composing styles

scripts/publishedPackages.json, src/eslint-fixtures-tester/.npmignore, src/eslint-fixtures-tester/LICENSE, src/eslint-fixtures-tester/package.json, src/eslint-plugin-adeira/package.json, src/eslint-plugin-sx/package.json, src/monorepo-shipit/config/__tests__/eslint-fixtures-tester.test.js, src/monorepo-shipit/config/eslint-fixtures-tester.js
Destination: https://github.com/adeira/eslint-fixtures-tester
=> Shipit + NPM: setup 'eslint-fixtures-tester' publishing

src/relay/CHANGELOG.md, src/relay/bin/fetch-schema.js
=> Relay: Fetch schema script options fix

src/example-relay/package.json, src/relay/CHANGELOG.md, src/relay/package.json, src/ya-comiste-backoffice/package.json
=> Release '@adeira/relay' version 3.2.0

src/sx-design/package.json, src/sx-design/translations/source_strings.json, src/sx-design/translations/src_manifest.json, src/ya-comiste-backoffice/package.json, yarn.lock
The new default `@fbtjs/default-collection-transform` transform dependency is needed unless you want to specify custom transformer via `--transform` Collect option, see: https://github.com/facebook/fbt/commit/1ce9a76f42b8b6bba684d91fadd05e72046ca13b
=> Fix FBT collection

src/sx-design/README.md
Accessibility is still one of the core values of this project, however, I don't know how to reliably evaluate it. So I'd rather remove it from the matrix and focus on it on demand.
=> SX Design: remove accessibility from the components matrix

src/eslint-config-adeira/CHANGELOG.md, src/eslint-config-adeira/__tests__/__snapshots__/index.test.js.snap, src/eslint-config-adeira/ourRules.js, src/kochka.com.mx/src/Rules.js, src/kochka.com.mx/src/SocialMediaIcons.js
Closes: https://github.com/adeira/universe/issues/2022
=> Eslint config: enable 'react/jsx-no-target-blank' rule

src/ya-comiste-rust/Cargo.lock
Still waiting for this PR to be able to ditch it completely: https://github.com/fMeow/arangors/pull/62
=> YCR: upgrade 'arangors' fork dependency

src/signedsource-rs/Cargo.toml, src/ya-comiste-rust/Cargo.toml
See: https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html
=> Rust: enable new 1.51.0 features

.github/dependabot.yml, src/example-relay/__github__/.github/workflows/continuous-integration.yml, src/sx-tailwind-website/__github__/.github/workflows/continuous-integration.yml
And also update Dependabot to maintain these files as well.
=> Update 'actions/setup-node' versions

.github/.kodiak.toml
See: https://kodiakhq.com/docs/config-reference#mergepriority_merge_label
=> Kodiak: setup 'priority_merge_label'

src/sx-tailwind-website/.babelrc.js, src/sx-tailwind-website/__github__/babel.config.js
Order of presets matter.
See https://vercel.com/adeira/universe-sx-tailwind-website/CA2YSPmFxQoh3cyrVUwr1nNezbe9
=> SXT Website: Fix preview build

src/kochka.com.mx/pages/_app.js, src/sx-design/.storybook/preview.js, src/sx-design/README.md, src/sx-design/src/Skeleton/Skeleton.js, src/sx-design/src/SxDesignContext.js, src/sx-design/src/SxDesignProvider.js, src/sx/__flowtests__/css-properties.js, src/sx/src/create.js, src/ya-comiste-backoffice/pages/_app.css, src/ya-comiste-backoffice/pages/_app.js, src/ya-comiste-backoffice/src/Layout.js, src/ya-comiste-backoffice/src/pos/POSCheckoutFailurePageLayout.js, src/ya-comiste-backoffice/src/pos/POSCheckoutPageLayout.js, src/ya-comiste-backoffice/src/pos/POSCheckoutSuccessPageLayout.js
This mode respects the OS settings. After this change, you can set "light" mode, "dark" mode or "system".
=> SX Design: add support for "system" dark mode

src/babel-preset-adeira/package.json, src/example-relay/package.json, src/fixtures-tester/package.json, src/flow-config-parser/package.json, src/graphql-bc-checker/package.json, src/monorepo-npm-publisher/package.json, src/monorepo-scanner/package.json, src/monorepo-shipit/package.json, src/sx/package.json
I am not aware of any issues or improvements which would be preventing stable release.
=> Release @adeira/fixtures-tester version 1.0.0

src/example-relay/__github__/.flowconfig, src/sx-tailwind-website/__github__/.flowconfig
Followup after 5f0c905ae627f670804581f78c1b570f3f71a1e6
=> Update exported `.flowconfig` files

src/sx-design/README.md, src/sx-design/index.js, src/sx-design/src/Note/Note.js, src/sx-design/src/Note/Note.stories.js, src/sx-design/translations/out/es-MX.json, src/sx-design/translations/source_strings.json, src/sx-design/translations/src_manifest.json, src/ya-comiste-backoffice/src/StatusBar.js, src/ya-comiste-backoffice/src/products/CreateProductForm.js, src/ya-comiste-backoffice/src/products/EditProductForm.js, src/ya-comiste-backoffice/src/products/EditProductHeading.js, src/ya-comiste-backoffice/src/products/EditProductHeadingPublishUnpublish.js, src/ya-comiste-backoffice/src/recoil/uiStatusBarAtom.js
=> SX Design: add `Note` component

src/monorepo-shipit/config/__tests__/sx-jest-snapshot-serializer.test.js, src/monorepo-shipit/config/sx-jest-snapshot-serializer.js
Destination: https://github.com/adeira/sx-jest-snapshot-serializer
=> Shipit: setup export for `sx-jest-snapshot-serializer`

src/sx-design/.storybook/preview.js, src/sx-design/README.md, src/sx-design/src/SxDesignProvider.js, src/sx-design/src/constants.js, src/sx-design/translations/in/no-NO.json, src/sx-design/translations/out/no-NO.json
Co-authored-by: Trond Bergquist <trond_bergquist@hotmail.com>
=> SX Design: add Norwegian language

src/example-relay/package.json, src/kochka.com.mx/package.json, src/relay/CHANGELOG.md, src/relay/package.json, src/ya-comiste-backoffice/package.json, yarn.lock
See: https://github.com/facebook/relay/releases/tag/v11.0.2
=> Use Relay version 11.0.2

src/__flowtests__/ReactElement.js, src/sx-design/src/Badge/Badge.stories.js, src/sx-design/src/Note/Note.js, src/sx-design/src/Note/Note.stories.js
This allows you to add any action button you want as long as it's `button` (or component rendering `button`).
=> SX Design: add `action` property to `Note` component

src/babel-preset-adeira/package.json, src/example-relay/package.json, src/fixtures-tester/CHANGELOG.md, src/fixtures-tester/package.json, src/flow-config-parser/package.json, src/graphql-bc-checker/package.json, src/monorepo-npm-publisher/package.json, src/monorepo-scanner/package.json, src/monorepo-shipit/package.json, src/sx/package.json
=> Fixtures tester: release version 1.0.1

babel.config.js, flow-typed/global.js, src/babel-plugin-transform-sx-tailwind/src/getCssDeclarations.js, src/babel-preset-adeira/src/index.js, src/eslint-plugin-sx/src/getRules.js, src/eslint-plugin-sx/src/index.js, src/eslint-plugin-sx/src/rules/utils/getSXImportSpecifiers.js, src/example-relay/__github__/babel.config.js, src/example-relay/jest.config.js, src/relay/bin/commander/options.js, src/sx-tailwind-website/__github__/babel.config.js, src/sx/README.md
Followup after https://github.com/adeira/universe/pull/1961 (some special types were not converted yet)
=> Flow: cleanup more exact objects

src/sx-design/.storybook/preview.js, src/sx-design/README.md, src/sx-design/src/SxDesignContext.js, src/sx-design/src/SxDesignProvider.js, src/sx-design/src/constants.js
LTR and RTL layouts are another important aspect of good design systems. I want to kick off this effort even though I do not have a real use case for RTL languages. I believe that applying additional constraints on this design system (and therefore SX itself) will help us make it more flexible and ready for more complex scenarios.
=> SX Design: kick off RTL support

src/abacus-backoffice/src/constants.js, src/abacus/Dockerfile, src/abacus/README.md, src/abacus/kubernetes/README.md, src/abacus/kubernetes/abacus.yaml, src/abacus/kubernetes/third_party/arangodb/arango-crd.yaml, src/abacus/kubernetes/third_party/arangodb/arango-deployment.yaml, src/abacus/kubernetes/third_party/arangodb/arango-storage.yaml, src/abacus/kubernetes/third_party/kubernetes/kubernetes-dashboard.yaml, src/abacus/src/main.rs
Still a lot of work but at least it kinda works.
=> Abacus: offload initial Kubernetes files

src/abacus-backoffice/src/constants.js, src/abacus/README.md, src/abacus/kubernetes/README.md, src/abacus/kubernetes/abacus.yaml, src/abacus/kubernetes/manual-arangodb-restore.yaml
Notable changes:
- switched to Telepresence for local remote development
- removed load balancer (to save money + not needed)
- applied some best practices from `kube-score`
- kicked off manual DB backup restoration
=> Abacus: update K8S files

src/kochka.com.mx/package.json, src/monorepo-shipit/bin/shipit.js, src/monorepo-shipit/config/__tests__/kochka.com.mx.test.js, src/monorepo-shipit/config/kochka.com.mx.js
It is not a perfect solution to be exporting it to my personal repository, I admit. I will take care of it. I am looking for a better solution but this is the most cost-effective for now.
=> Shipit: setup exports for kochka.com.mx

src/monorepo-shipit/config/__tests__/monorepo-npm-publisher.test.js, src/monorepo-shipit/config/monorepo-npm-publisher.js
Destination: https://github.com/adeira/monorepo-npm-publisher
=> Shipit: setup `monorepo-npm-publisher`

src/abacus-backoffice/pages/_app.js, src/abacus-backoffice/src/NavigationHeader.js, src/abacus-backoffice/src/products/ProductsCards.js, src/abacus-backoffice/src/products/ProductsEditLayout.js, src/abacus-backoffice/src/products/__generated__/ProductsCardsQuery.graphql.js, src/abacus-backoffice/src/products/__tests__/createProductFormSchema.test.js, src/abacus-backoffice/src/useApplicationLocale.js, src/abacus-backoffice/translations/init.js
This allows us to call GraphQL operations with the correct application locale.
=> Abacus BO: add `useApplicationLocale` hook

.github/dependabot.yml
=> Dependabot: Ignore Refractor updates

package.json, src/abacus-backoffice/src/pos/recoil/selectedItemsState.js, src/abacus-backoffice/src/products/EditProductHeadingPublishUnpublish.js, src/eslint-fixtures-tester/src/index.js, src/eslint-plugin-adeira/src/rules/__tests__/only-nullable-fields.test.js, src/eslint-plugin-adeira/src/rules/__tests__/relay-import-no-values.test.js, src/example-relay/src/components/Navbar.module.css, src/example-relay/src/styles/app.css, src/flow-config-parser/src/merge.js, src/graphql-relay/src/mutation/mutation.js, src/kochka.com.mx/src/LanguageTag.js, src/sx-tailwind-website/public/code-block.css, src/sx/src/StyleCollector.js, src/sx/src/__tests__/fixtures/@supports.js
Followup after: https://github.com/adeira/universe/pull/2364
See: https://prettier.io/blog/2021/05/09/2.3.0.html
=> Fix Prettier 2.3.0 issues

scripts/package.json
Use latest version of `@adeira/flow-config-parser`
=> Internal scripts: Fix deps

src/abacus/Cargo.lock, src/abacus/Cargo.toml, src/abacus/src/images/mod.rs, src/abacus/src/migrations/snapshots/server__migrations__v4__create_collection_products__tests__products_json_schema_validation_test-2.snap, src/abacus/src/migrations/snapshots/server__migrations__v4__create_collection_products__tests__products_json_schema_validation_test.snap
This removes some unnecessary dependencies which reduces compile time.
=> Abacus: specify features of some crates explicitly

src/abacus-backoffice/Dockerfile, src/abacus-backoffice/README.md, src/abacus-backoffice/package.json, src/abacus/README.md
Inspired by this Next.js recommendation: https://github.com/vercel/next.js/blob/989056598329e23b6d019e5cbe244c623c1b4afa/docs/deployment.md#docker-image
=> Abacus BO: add basic Dockerfile

.github/workflows/dockerfile-builder.yml
This change also adds a new `docker/metadata-action` GitHub Action to generate additional tags and labels (not just `image:latest`).
TODO:
=> Dockerfile builder: add Abacus BO

.github/workflows/continuous-integration-javascript.yml, src/example-relay/__github__/.github/workflows/continuous-integration.yml, src/sx-tailwind-website/__github__/.github/workflows/continuous-integration.yml
Version 15 is dead, see: https://nodejs.org/en/about/releases/
=> CI: remove Node.js 15

src/abacus-backoffice/package.json, src/kochka.com.mx/package.json, src/kochka.com.mx/src/menu/MenuSectionTea.js, src/sx-design/README.md, src/sx-design/index.js, src/sx-design/package.json, src/sx-design/src/Temperature/Temperature.js, src/sx-design/src/Temperature/Temperature.stories.js, src/sx-design/src/Temperature/__tests__/Temperature.test.js
This component renders the correct temperature unit based on the active locale.
=> SX Design: add `Temperature` component

src/abacus-kochka/src/__tests__/LanguageTag.test.js, src/abacus-kochka/src/__tests__/Layout.test.js
See: https://github.com/adeira/universe/pull/2258
There were previously some weird problems with running these tests, but I'd like to try again since the project has a different name now (might have been the issue).
=> Abacus KO: revert 5baf305ceedb81d3cb9ce8116ecdb3a9df7f899f

.github/workflows/continuous-integration-javascript.yml, .github/workflows/continuous-integration-rust.yml, .github/workflows/dockerfile-builder.yml
To improve readability of the CI output.
=> JavaScript CI: split one big step into multiple steps

src/abacus-kochka/src/__tests__/LanguageTag.test.js, src/abacus-kochka/src/__tests__/Layout.test.js
See: https://github.com/babel/babel/issues/13462
=> Abacus KO: skip failing tests

src/abacus/src/auth/certs.rs, src/abacus/src/auth/google.rs
No idea why it started failing now and how it got to the master.
=> Abacus: fix failing tests

src/monorepo-shipit/config/__tests__/sx-tailwind.test.js, src/monorepo-shipit/config/sx-tailwind.js
Destination: https://github.com/adeira/sx-tailwind
=> Shipit: setup SX Tailwind exports

src/sx-design/src/SxDesignPortal.js, src/sx-design/src/SxDesignProvider.js, src/sx-design/src/Tooltip/Tooltip.js, src/sx-design/src/Tooltip/Tooltip.stories.js, src/sx-design/src/Tooltip/__tests__/Tooltip.test.js, src/sx-design/src/Tooltip/__tests__/findBestTooltipPosition.test.js, src/sx-design/src/Tooltip/findBestTooltipPosition.js
This allows us to position to `Tooltip` component better when there is not enough space.
=> SX Design: implement `findBestTooltipPosition`

.flowconfig, .flowconfig.template.base, flow-typed/fbt.js, src/relay/src/__flowtests__/mutations.js, src/relay/src/getDataFromRequest.js, src/relay/src/mutations.js, src/relay/src/types.flow.js, src/relay/src/useLazyLoadQuery.js, src/relay/src/useMutation.js
For more information visit: https://flow.org/en/docs/types/indexed-access/
=> Flow: use Indexed Access Types

src/graphql-relay/src/connection/connection.js, src/graphql-relay/src/mutation/mutation.js, src/graphql-relay/src/node/node.js, src/graphql-relay/src/node/plural.js
Via codemod:
```text
yarn flow codemod replace-existentials --write .
```
=> Flow: replace existential types

src/abacus-backoffice/src/forms/FormSelect.js, src/abacus-backoffice/src/forms/FormSelectOption.js, src/abacus-backoffice/src/forms/__tests__/FormSelect.test.js, src/abacus-backoffice/src/forms/private/BaseSelect.js, src/abacus-backoffice/src/products/ProductCreateForm.js, src/abacus-backoffice/src/products/ProductEditForm.js, src/abacus-backoffice/src/products/ProductForm.js, src/abacus-backoffice/src/products/__generated__/ProductEditFormData.graphql.js, src/abacus-backoffice/src/products/__generated__/ProductEditFormMutation.graphql.js, src/abacus-backoffice/src/products/__generated__/ProductsEditLayoutQuery.graphql.js
Related issue: https://github.com/adeira/universe/issues/2640
=> Abacus: use selected categories when editing product

src/abacus/Cargo.lock, src/abacus/Cargo.toml, src/abacus/src/arangodb/mod.rs, src/abacus/src/arangors/client/mod.rs, src/abacus/src/arangors/client/reqwest.rs, src/abacus/src/arangors/collection/mod.rs, src/abacus/src/arangors/connection/mod.rs, src/abacus/src/arangors/database.rs, src/abacus/src/arangors/error.rs, src/abacus/src/arangors/mod.rs, src/abacus/src/arangors/transaction.rs, src/abacus/src/auth/google.rs
It has the same maintenance issues as `arangors` (same owner).
=> Abacus: remove `uclient` dependency

src/abacus/kubernetes/README.md, src/abacus/kubernetes/abacus.yaml, src/abacus/kubernetes/manual-arangodb-restore.yaml
Related issue: https://github.com/adeira/universe/issues/2848
=> Abacus: upgrade to ArangoDB version 3.7.13

src/abacus/kubernetes/README.md, src/abacus/kubernetes/abacus.yaml, src/abacus/kubernetes/manual-arangodb-restore.yaml, src/abacus/src/commerce/dal/product_categories.rs
See: https://www.arangodb.com/docs/3.8/release-notes-38.html
=> Abacus: upgrade to ArangoDB version 3.8.0

src/abacus-backoffice/package.json, src/abacus-kochka/package.json, src/icons/package.json, src/sx-design/package.json
I am not aware of anything that should be done here. It just works.
=> Release `@adeira/icons` version 1.0.0

src/eslint-config-adeira/CHANGELOG.md, src/eslint-config-adeira/README.md, src/eslint-config-adeira/__tests__/__snapshots__/presets.test.js.snap, src/eslint-config-adeira/__tests__/next.test.js, src/eslint-config-adeira/__tests__/presets.test.js, src/eslint-config-adeira/next.js, src/eslint-config-adeira/package.json, src/eslint-config-adeira/src/presets/next.js, src/example-relay/.eslintrc.js, src/example-relay/src/pages/_document.js, yarn.lock
Supersedes https://github.com/adeira/universe/pull/2562
=> Eslint config: add new Next.js subset

src/abacus/src/commerce/dal/product_categories.rs, src/abacus/src/commerce/dal/products.rs, src/abacus/src/commerce/model/products.rs
Related issue: https://github.com/adeira/universe/issues/2673
=> Abacus: assign product addons when creating/editing products

src/abacus-kochka/next.config.js, src/abacus-kochka/pages/_app.js, src/abacus-kochka/src/Menu.js, src/abacus-kochka/src/RelayEnvironment.js, src/abacus-kochka/src/menu/MenuLoader.js, src/abacus-kochka/src/shop/ShopLayoutContent.js
=>  Abacus KO: use fetch policy `store-and-network` in query renderers 

src/abacus-backoffice/src/pos/POSAllSessionsPageLayout.js, src/abacus-backoffice/translations/source_strings.json, src/sx-design/src/Link/LinkButton.js, src/sx-design/src/Link/LinkButton.stories.js, src/sx-design/src/Link/__tests__/LinkButton.test.js
Similar to the same props in `Button` component`.
=> SX Design: add support for `prefix`/`suffix` props in `LinkButton`

src/abacus/kubernetes/abacus.yaml, src/abacus/kubernetes/manual-arangodb-restore.yaml
See: https://github.com/arangodb/arangodb/blob/v3.8.1/CHANGELOG
=> Abacus: upgrade ArangoDB to version 3.8.1

.flowconfig, .flowconfig.template.base, src/babel-preset-adeira/CHANGELOG.md, src/babel-preset-adeira/README.md, src/babel-preset-adeira/package.json, src/babel-preset-adeira/src/__tests__/__fixtures__/features/flow-enums.js, src/babel-preset-adeira/src/__tests__/__snapshots__/configs.test.js.snap, src/babel-preset-adeira/src/__tests__/__snapshots__/transformations.test.js.snap, src/babel-preset-adeira/src/index.js, src/eslint-config-adeira/CHANGELOG.md, src/eslint-config-adeira/__tests__/__fixtures__/valid-eslint-examples/flow/enums.js, src/eslint-config-adeira/__tests__/__snapshots__/index.test.js.snap, src/eslint-config-adeira/__tests__/__snapshots__/presets.test.js.snap, src/eslint-config-adeira/src/presets/base.js, src/eslint-config-adeira/src/presets/flowtype.js, yarn.lock
See: https://flow.org/en/docs/enums/
=> Universe: enable Flow Enums

src/sx-design/.eslintrc.js, src/sx-design/package.json, src/sx-design/src/Badge/__tests__/Badge.test.js, src/sx-design/src/Button/__tests__/Button.test.js, src/sx-design/src/Button/__tests__/ButtonLink.test.js, src/sx-design/src/Chips/__tests__/FilterChips.test.js, src/sx-design/src/ErrorBoundary/__tests__/ErrorBoundary.test.js, src/sx-design/src/Link/__tests__/Link.test.js, src/sx-design/src/Link/__tests__/LinkButton.test.js, src/sx-design/src/Menu/__tests__/Menu.test.js, src/sx-design/src/MissingData/__tests__/MissingData.test.js, src/sx-design/src/Modal/__tests__/Modal.test.js, src/sx-design/src/Tabs/__tests__/Tabs.test.js, src/sx-design/src/Tooltip/__tests__/Tooltip.test.js, src/sx-design/src/test-utils.js, yarn.lock
See: https://testing-library.com/docs/ecosystem-user-event
=> SX Design: replace `fireEvent` with `userEvent`

src/example-relay/.babelrc.js, src/example-relay/__github__/babel.config.js, src/example-relay/next.config.js
=> Relay example: lazy load `@adeira/icons`

flow-typed/msw.js, src/fetch/jest.config.js, src/fetch/package.json, src/fetch/scripts/setupJest.js, src/fetch/src/__tests__/fetchWithRetries.200.test.js, src/fetch/src/__tests__/fetchWithRetries.403.test.js, src/fetch/src/__tests__/fetchWithRetries.FormData.test.js, src/fetch/src/__tests__/fetchWithRetries.GET.test.js, src/fetch/src/__tests__/fetchWithRetries.POST.test.js, src/fetch/src/__tests__/fetchWithRetries.failAfterRetries.test.js, src/fetch/src/__tests__/fetchWithRetries.fetchError.test.js, src/fetch/src/__tests__/fetchWithRetries.retries.test.js, src/fetch/src/__tests__/fetchWithRetries.retryAfterFail.test.js, src/fetch/src/__tests__/fetchWithRetries.timeout.test.js, src/fetch/src/__tests__/fetchWithRetries.timeoutZero.test.js, src/fetch/src/test-utils.js, yarn.lock
=> fetch: use real timers

src/abacus-kochka/src/shop/ShopLayout.js
Still not great but a small step forward.
=> Abacus KO: improve design

src/abacus-backoffice/src/index/IndexPage.js, src/abacus-backoffice/src/index/__generated__/IndexPageQuery.graphql.js, src/abacus-backoffice/translations/out/es_MX.json, src/abacus-backoffice/translations/source_strings.json
Most sold products are enough for now.
=> Abacus BO: remove "least sold products" from analytics

src/abacus/src/auth/mod.rs
We need to keep the old sessions with new authorization so that we can
login with multiple devices.
=> Abacus: do not destroy old sessions

src/example-relay/src/pages/_document.js
See: https://nextjs.org/docs/messages/missing-document-component
=> Relay example: fix "Missing Document Components" Next.js error

src/babel-preset-adeira/package.json, src/example-relay/package.json, src/fixtures-tester/package.json, src/flow-config-parser/package.json, src/graphql-bc-checker/package.json, src/monorepo-scanner/package.json, src/monorepo-shipit/package.json, src/sx/package.json
Internal changes and dependency upgrades.
=> Fixtures tester: release 1.1.1

.github/workflows/continuous-integration-javascript.yml, src/abacus-backoffice/package.json, src/abacus-kochka/package.json, src/example-relay/package.json, src/relay/CHANGELOG.md, src/relay/package.json, yarn.lock
See: https://github.com/facebook/relay/releases/tag/v13.0.2
=> Relay: use version 13.0.2

src/example-relay/package.json, src/relay/CHANGELOG.md, src/relay/package.json, yarn.lock
See: https://github.com/facebook/relay/releases/tag/v13.1.1
=> Relay: use version 13.1.1

src/abacus-backoffice/src/LanguageSwitch.js, src/abacus-kochka/src/LanguageSwitch.js, src/eslint-config-adeira/__tests__/__snapshots__/presets.test.js.snap, src/eslint-config-adeira/src/presets/next.js
These got introduced with the latest Next.js plugin upgrade by accident.
=> URGENT: Fix lint errors on master

src/sx-design/.storybook/SxDesignTheme.js
It got broken somewhere on the way because of the `$FlowFixMe` annotation.
=> SX Design: fix Storybook

src/abacus-kochka/README.md
Basically remove almost everything because it's outdated.
=> Abacus KO: update README.md

src/abacus-kochka/translations/in/es_MX.json, src/abacus-kochka/translations/out/es_MX.json
No idea how this happened and unfortunately I don't have time to investigate further.
=> Abacus KO: fix `es_MX` translations

src/abacus-kochka/src/LanguageSwitch.js, src/abacus-kochka/src/SocialMediaIcons.js, src/example-relay/src/mutations/LocationsList.js
This fixes broken master, again.
See: https://github.com/weiran-zsd/eslint-plugin-node/issues/11
=> Eslint: suppress `n/file-extension-in-import` in some files

src/abacus/server/src/warp_server/filters.rs
=> Abacus: allow `business` subdomain

src/abacus/kubernetes/abacus.yaml, src/abacus/server/src/warp_server/filters.rs
We are now using `business.kochka.com.mx`.
=> Abacus Ingress, CORS: remove `abacus-bo` subdomain

src/abacus-backoffice/src/pos/ProductsGridCategories.js, src/abacus-backoffice/src/products/ProductsCategories.js, src/sx-design/__flowtests__/Tabs.js, src/sx-design/index.js, src/sx-design/src/Tabs/Tabs.js
=> SX Design: improve typing of `Tabs` properties

.yarn/versions/a7c167dd.yml, src/abacus-kochka/package.json, src/abacus-kochka/pages/_app.js, yarn.lock
=> Abacus KO: remove AXE

flow-typed/fbt.js
See: https://github.com/facebook/fbt/blob/25177e9391f81c017c9afbf74f709d48ef7a882a/docs/enforcing_plain_text.md
=> Update Flow types to support FBS

.gitattributes
As mentioned here: https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored
=> Gitattributes: update for Yarn Berry

README.md
See for more details: https://yarnpkg.com/getting-started/install
=> README: update "Quick start" to use Corepack

.github/workflows/codeql-analysis.yml, .github/workflows/continuous-integration-javascript.yml, .github/workflows/continuous-integration-rust.yml, .github/workflows/dockerfile-builder.yml, .github/workflows/npm-publisher.yml, .github/workflows/playwright.yml, .github/workflows/shipit.yml
To split dependency installation and publishing.
=> CI: update NPM publisher workflow

src/sx-design/.storybook/main.js
See: https://github.com/storybookjs/storybook/issues/16690
=> SX Design: workaround Storybook bug

.yarn/patches/ip-npm-1.1.5-af36318aa6.patch, package.json, src/sx-design/.storybook/main.js, yarn.lock
See: https://github.com/storybookjs/storybook/issues/18019
Should we resolved in `ip` version 1.1.6 or 2.0.0, see: https://github.com/indutny/node-ip/commit/4de50aec875d12b004849e11e19d6daf68b50c2d
=> SX Design: patch 3rd party dependency

.github/workflows/playwright.yml, src/abacus-backoffice/package.json, src/abacus-backoffice/pages/_app.js, src/abacus-backoffice/playwright.config.js, src/abacus-backoffice/tests/.eslintrc.js, src/abacus-backoffice/tests/README.md, src/abacus-backoffice/tests/ui/homepage.play.js, yarn.lock
Just to make sure the application can start successfully.
=> Abacus BO: enable minimal Playwright test

.github/workflows/daily-rust-cargo-update.yml
See: https://github.com/peter-evans/create-pull-request#alternative-strategy---always-create-a-new-pull-request-branch
=> CI: improve daily Cargo workflow strategy

.github/workflows/daily-rust-cargo-update.yml
See: https://github.com/peter-evans/create-pull-request/blob/f094b77505fb89581e68a1163fbd2fffece39da1/docs/concepts-guidelines.md#triggering-further-workflow-runs
=> CI: use `PAT` secret for daily Rust Cargo workflow

src/abacus-backoffice/src/index/DailyIncomeMeter.js
=> Abacus BO: update `DailyIncomeMeter` values

src/relay/README.md
Remove deprecated information.
=> Relay: update README.md

src/sx-design/src/Image/Image.js
This reverts commit eb4aefcd8bd35a221dc76db523a3afdc30efe675.
Closes: https://github.com/adeira/universe/issues/4509
=> Revert "SX Design: lazy-load all images by default"

.github/workflows/playwright.yml, src/abacus-docs/package.json, src/abacus-docs/playwright.config.js, src/abacus-docs/playwright/.eslintrc.js, src/abacus-docs/playwright/README.md, src/abacus-docs/playwright/ui/homepage.play.js, yarn.lock
To make sure our docs work as expected.
=> Abacus Docs: init Playwright tests

src/abacus/server/src/warp_server/handlers.rs
The webhooks are not ready yet, but I'd like to start capturing them to the console.
=> Abacus: `dbg` print WLCM.app webhook payloads

src/abacus-backoffice/src/ErrorBoundaryEmpty.js, src/abacus-backoffice/src/Navigation.js, src/abacus-backoffice/src/NavigationHeader.js, src/abacus-backoffice/src/NavigationHeaderBadge.js, src/abacus-backoffice/src/__generated__/NavigationHeaderBadgeQuery.graphql.js
This reverts commit 9f897f519eed2a9f3ec595a9dcb599da5906ec5b.
=> Revert "Abacus BO: remove `NavigationHeaderBadge.js`"

src/abacus-kochka/pages/unstable_sitemap.xml.js, src/abacus-kochka/playwright/ui/sitemap.play.js, src/abacus-kochka/public/robots.txt
=> Abacus KO: temporarily disable sitemap

x
Inspired by: https://github.com/dtolnay/rust-toolchain
=> X: automatically install Rust if missing

.github/workflows/continuous-integration-javascript.yml
See: https://github.com/actions/setup-node/issues/325
=> CI: use custom (better) Yarn cache strategy

src/abacus/server/src/menu/mod.rs
Closes: https://github.com/adeira/universe/issues/4781
=> Abacus: remove "Arroz Snowball"

.flowconfig, src/eslint-config-adeira/src/EslintConfig.flow.js, src/eslint-config-adeira/src/getCommonConfig.js, src/monorepo-utils/src/Git.js, src/monorepo-utils/src/Workspaces.js, src/sx/src/StyleCollectorPseudoNode.js
```
flow codemod annotate-declarations
```
=> Flow: enable new inference mode (`constrain_writes`)

.flowconfig, src/js/src/sprintf.js, src/js/src/warning.js
=> Flow: codemod `src/js` (`annotate-lti-experimental`)

src/eslint-plugin-adeira/src/rules/__tests__/fixtures/no-unmasked-graphql-id-without-alias/invalid/missing-alias-deep.js, src/eslint-plugin-adeira/src/rules/__tests__/fixtures/no-unmasked-graphql-id-without-alias/invalid/missing-alias.js, src/eslint-plugin-adeira/src/rules/__tests__/fixtures/no-unmasked-graphql-id-without-alias/valid/aliased-id.js, src/eslint-plugin-adeira/src/rules/__tests__/fixtures/no-unmasked-graphql-id-without-alias/valid/opaque-id.js, src/eslint-plugin-adeira/src/rules/__tests__/fixtures/no-unmasked-graphql-id-without-alias/valid/unrelated-fields.js, src/eslint-plugin-adeira/src/rules/no-invalid-flow-annotations.js, src/eslint-plugin-adeira/src/rules/no-unmasked-graphql-id-without-alias.js
=> Flow: codemod `src/eslint-plugin-adeira` (`annotate-lti-experimental`)

src/abacus-backoffice/src/AuthButtons.js, src/abacus-backoffice/src/LayoutHeadingButton.js, src/abacus-backoffice/src/pos/ProductsGridModalBody.js, src/abacus-backoffice/src/products/ProductEditHeading.js, src/abacus-backoffice/src/products/ProductsEditLayout.js
=> Flow: partially codemod `src/abacus-backoffice` (`annotate-lti-experimental`)

src/css-colors/src/convertToRGBTriplet.js
=> Flow: codemod `src/css-color` (`annotate-lti-experimental`)

src/sx/src/__tests__/expandShorthandProperties.test.js, src/sx/src/injectRuntimeStyles.js, src/sx/src/shorthand-properties/expandMarginPadding.js
=> Flow: partially codemod `src/sx` (`annotate-lti-experimental`)

src/forms/src/FormSubmit.js, src/forms/src/private/useFormFieldState.js
=> Flow: codemod `src/forms` (`annotate-lti-experimental`)

src/abacus-kochka/src/NavigationLinks.js
=> Flow: codemod `src/abacus-kochka` (`annotate-lti-experimental`)

src/relay/src/__flowtests__/Environment.js, src/relay/src/internal/__tests__/createRequestHandler.test.js, src/relay/src/internal/helpers.js, src/relay/src/useMutation.js
=> Flow: codemod `src/relay` (`annotate-lti-experimental`)

src/flow-config-parser/src/parse.js
=> Flow: codemod `src/flow-config-parser` (`annotate-lti-experimental`)

src/hooks/src/useSessionTokenAPI.js
=> Flow: codemod `src/hooks` (`annotate-lti-experimental`)

src/eslint-config-adeira/__tests__/__fixtures__/invalid-eslint-examples/react/no-unused-vars.js, src/eslint-config-adeira/__tests__/__fixtures__/valid-eslint-examples/flow/exhaustive-checking.js, src/eslint-config-adeira/__tests__/__fixtures__/valid-eslint-examples/react/jsx-no-bind.js, src/eslint-config-adeira/__tests__/__fixtures__/valid-eslint-examples/tagged-templates.js
=> Flow: codemod `src/eslint-config-adeira` (`annotate-lti-experimental`)

src/sx-design/src/Chips/FilterChips.js, src/sx-design/src/ErrorBoundary/ErrorBoundary.stories.js, src/sx-design/src/Link/LinkButton.js, src/sx-design/src/Loader/Loader.js, src/sx-design/src/Modal/__tests__/Modal.test.js, src/sx-design/src/Tooltip/__tests__/findBestTooltipPosition.test.js
=> Flow: codemod `src/sx-design` (`annotate-lti-experimental`)

src/fetch/src/ResponseError.js, src/fetch/src/TimeoutError.js, src/fetch/src/fetchWithRetries.js
=> Flow: codemod `src/fetch` (`annotate-lti-experimental`)

babel.config.js, scripts/jest/setupTests.js, src/shell-command/src/ShellCommand.js
=> Flow: codemod `src/shell-command` (`annotate-lti-experimental`)

src/abacus/server/src/stripe/dal.rs
It happened before that we saved the webhook payload to our database successfully, however server returned 503 because something got broken along the way. Later when Stripe retried to send the payload, our DB failed on "unique constraint violated" error because the event was already recorded.
This should fix this situation.
=> Abacus: ignore already existing Stripe events

src/sx-design/playwright/ui/badge.play.js, src/sx-design/playwright/ui/homepage.play.js
Via:
```
npx playwright codegen https://sx-design.vercel.app/
```
\+ manual modifications
=> SX Design: generate Playwright test for `Badge` component

relay.config.js, src/abacus/schema.graphql, src/abacus/server/src/auth/users/mod.rs
See: https://github.com/facebook/relay/commit/d0a39283d45854922119b779c4ac7014fd402d20
=> Relay: enforce correct type for `id` fields

.github/workflows/shellcheck.yml
Closes: https://github.com/adeira/universe/issues/5188
=> CI: add `shellcheck`

.flowconfig, package.json, src/__flowtests__/ReactElement.js, src/abacus-backoffice/src/pos/POSCheckoutPageLayout.js, src/abacus-backoffice/src/pos/ProductsGrid.js, src/abacus-backoffice/src/pos/recoil/__tests__/selectedItemsState.test.js, src/abacus-backoffice/src/pos/recoil/selectedItemsState.js, src/abacus-docs/pages/_app.js, src/eslint-config-adeira/__tests__/__fixtures__/valid-eslint-examples/react/jsx-no-bind.js, src/eslint-plugin-adeira/src/rules/no-unmasked-graphql-id-without-alias.js, src/monorepo-shipit/src/__tests__/RepoGit.findFirstAvailableCommit.test.js, src/sx/src/StyleCollector.js, src/sx/src/StyleCollectorNode.js, src/sx/src/create.js, yarn.lock
Closes: https://github.com/adeira/universe/issues/5030
=> Flow: upgrade to version 0.189.0

src/sx-design/package.json, src/sx-design/src/DateTime/__tests__/DateTime.test.js, src/sx-design/src/Money/__tests__/Money.test.js, yarn.lock
Some language specific things changes thanks to ICU 72.1 upgrade (see: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V19.md#19.1.0).
=> Fix support for Node.js 19.1.0

src/abacus-backoffice/next.config.js, src/abacus-kochka/next.config.js
See: https://nextjs.org/docs/advanced-features/security-headers
=> Abacus KO: configure security headers

src/abacus-kochka/src/shop/ShopLayout.js, src/sx-design-wlcm/src/types.js, src/sx-design/src/types.js
See: https://github.com/facebook/flow/commit/dd578274e90739c77bf9050dd1d2d6aa6866e080
=> Flow: replace `$Shape<T>` with `$Partial<T>`

src/x/src/main.rs
=> X: do not run `yarn install` by default

src/babel-preset-adeira/src/__tests__/__snapshots__/transformations.test.js.snap, yarn.lock
It's currently failing on CI. This will be done automatically in the future.
=> Update `caniuse-lite` dependency

src/abacus-backoffice/playwright.config.js, src/abacus-docs/playwright.config.js, src/abacus-kochka/playwright.config.js, src/sx-design/playwright.config.js
See: https://playwright.dev/docs/test-configuration
=> Playwright: improve configuration

.github/workflows/continuous-integration-javascript.yml, .github/workflows/continuous-integration-rust.yml, .github/workflows/weekly-rust-cargo-update.yml, src/abacus/Dockerfile
=> Revert "CI: use explicit Rust version"

src/abacus-kubernetes/abacus/arangodb.yaml, src/abacus-kubernetes/manual-arangodb-restore.yaml
=> Abacus K8s: use `arangodb/arangodb:3.10.5.2`

.github/renovate.json5
=> Revert "Renovate: group Flow packages"

src/abacus-kubernetes/abacus/arangodb.yaml, src/abacus-kubernetes/manual-arangodb-restore.yaml
=> Abacus K8s: use ArangoDB v3.10.6

src/monorepo-shipit/package.json
=> Shipit: release version 0.2.0

src/monorepo-shipit/src/requireAndValidateConfig.js
This pull request:
- adds `transformCommitMessage` to allow config values
**TODO**
=> chore: allow commit transform

src/monorepo-shipit/package.json
=> Shipit: release version 0.2.1

.github/workflows/shipit.yml, src/monorepo-shipit/README.md, src/monorepo-shipit/package.json
=> Shipit: improve README

src/rossum-hooks/src/string-manipulations/index.js
This should no longer be necessary thanks to the latest product changes.
=> Rossum hooks (string-manipulations): remove wrapping try/catch

src/babel-preset-adeira/src/__tests__/__snapshots__/transformations.test.js.snap, src/babel-preset-adeira/src/__tests__/transformations.test.js
=> Babel preset: remove old snapshot tests

src/homebrew-universe/Formula/test.rb, src/homebrew-universe/README.md
Just to test some future changes instead of breaking the "production" formula.
=> Homebrew: add "test" formula

src/homebrew-universe/Formula/rossum-dmv2-analyze.rb, src/homebrew-universe/README.md
This adds support for ARM and Intel architectures.
=> Homebrew: update `rossum-dmv2-analyze` formula

src/rossum-dmv2-analyze/Cargo.lock, src/rossum-dmv2-analyze/Cargo.toml, src/rossum-dmv2-analyze/README.md, src/rossum-dmv2-analyze/src/api.rs, src/rossum-dmv2-analyze/src/clap.rs, src/rossum-dmv2-analyze/src/dmv2.rs, src/rossum-dmv2-analyze/src/export.rs, src/rossum-dmv2-analyze/src/main.rs, src/rossum-dmv2-analyze/src/processor.rs
This allows downloading of the new results from DMv2.
=> Rossum DMv2 analyze: add export functionality

.flowconfig
See: https://flow.org/en/docs/react/multiplatform
=> Flow: enable experimental multiplatform support

.github/workflows/continuous-integration-javascript.yml, package.json, tsconfig.json, yarn.config.cjs, yarn.lock
https://yarnpkg.com/features/constraints
=> Yarn: enable constraints

src/sx-design/src/DateTime/__tests__/DateTime.test.js, src/sx-design/src/Money/__tests__/Money.test.js
See: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V21.md#21.3.0
=> Update test cases to address the latest changes in ICU 74.1

src/abacus-backoffice/src/LayoutHeadingLink.js, src/abacus-backoffice/src/analytics/AnalyticsRedirectsPage.js, src/abacus-backoffice/src/pos/POSAllSessionsPageLayout.js, src/abacus-backoffice/src/pos/POSCheckoutPageLayout.js, src/abacus-backoffice/src/pos/POSCheckoutSuccessPageLayout.js, src/abacus-kochka/src/HomepageFooter.js, src/abacus-kochka/src/LayoutFooter.js, src/abacus-kochka/src/donations/DonationsOneTime.js, src/abacus-kochka/src/donations/DonationsRecurring.js, src/abacus-kochka/src/primitives/Link.js, src/sx-design/.storybook/main.js, src/sx-design/.storybook/preview.js, src/sx-design/__flowtests__/LinkButton.js, src/sx-design/__flowtests__/Text.js, src/sx-design/package.json, src/sx-design/src/Breadcrumb/Breadcrumb.stories.js, src/sx-design/src/Breadcrumb/BreadcrumbItem.js, src/sx-design/src/Breadcrumb/__tests__/Breadcrumb.test.js, src/sx-design/src/Link/Link.js, src/sx-design/src/Link/LinkButton.js, src/sx-design/src/Link/__tests__/Link.test.js, src/sx-design/src/Link/__tests__/LinkButton.test.js, src/sx-design/src/LocaleSwitcher/LocaleSwitcher.js, src/sx-design/src/LocaleSwitcher/LocaleSwitcher.stories.js, yarn.lock
There is still a bit of ugliness in `Link` and `LocaleSwitcher` but it's mostly decoupled now.
=> SX Design: decouple from Next.js

src/abacus/server/src/arango/connection/auth.rs, src/abacus/server/src/arango/connection/mod.rs, src/abacus/server/src/arango/mod.rs, src/abacus/server/src/auth/google.rs, src/abacus/server/src/commerce/model/products.rs, src/abacus/server/src/migrations/utils/mod.rs, src/abacus/server/src/warp_server/handlers.rs
Via: `cargo clippy --fix --bin "server"`
=> Abacus: apply automatic Clippy fixes

src/rossum-sa-extension/scripts/list-selector-improvements.js
Closes: https://github.com/adeira/universe/issues/7242
=> Rossum SA ext: fix sorting of irrelevant lists

src/monorepo-npm-publisher/README.md, src/monorepo-npm-publisher/src/utils/transformFileVariants.js
In effort to make adeira/universe less weird.
=> NPM publisher: remove support for `*-ADEIRA-UNIVERSE-INTERNAL` comments

src/abacus/Cargo.lock, src/abacus/server/Cargo.toml, src/abacus/server/src/axum_server/mod.rs, src/abacus/server/src/main.rs
Warp is going to be removed once we migrate to Axum.
=> Abacus: use Axum

src/abacus-backoffice/pages/_app.js, src/abacus-backoffice/src/constants.js, src/abacus/README.md, src/abacus/mirrord.json, src/abacus/server/src/__snapshots__/server__clap__tests__generated_clap_usage_test_long_help.snap, src/abacus/server/src/__snapshots__/server__clap__tests__generated_clap_usage_test_short_help.snap, src/abacus/server/src/clap.rs, src/abacus/server/src/main.rs, src/kubernetes/README.md, src/kubernetes/abacus/abacus.yaml, src/kubernetes/abacus/arangodb.yaml, src/kubernetes/manual-arangodb-restore.yaml
=> Abacus: use `mirrord` for local development

.flowconfig
See: https://github.com/facebook/flow/releases/tag/v0.237.0
=> Flow: enable Jest integration

.github/workflows/playwright.yml, src/mrtnzlml.com/.babelrc.js, src/mrtnzlml.com/.eslintrc.js, src/mrtnzlml.com/.gitignore, src/mrtnzlml.com/Dockerfile, src/mrtnzlml.com/README.md, src/mrtnzlml.com/next.config.js, src/mrtnzlml.com/package.json, src/mrtnzlml.com/playwright.config.js, src/mrtnzlml.com/playwright/.eslintrc.js, src/mrtnzlml.com/playwright/pages/index.play.js, src/mrtnzlml.com/src/app/_global.css, src/mrtnzlml.com/src/app/layout.js, src/mrtnzlml.com/src/app/page.js, yarn.lock
=> Add new repo `mrtnzlml.com`

src/monorepo-shipit/src/__tests__/__snapshots__/parsePatch.test.js.snap, src/monorepo-shipit/src/__tests__/__snapshots__/parsePatchHeader.test.js.snap
Something changes. Don't have time to investigate further.
=> Update Jest snapshots

src/rossum-sa-extension/README.md, src/rossum-sa-extension/popup/popup.css, src/rossum-sa-extension/popup/popup.html, src/rossum-sa-extension/popup/popup.js, src/rossum-sa-extension/scripts/rossum.js
It is no longer needed as it was added directly to the product.
=> Rossum SA ext: remove `localUnleashOverrides` functionality

src/rossum-sa-extension/manifest.json, src/rossum-sa-extension/package.json, src/rossum-sa-extension/popup/popup.html
[rossum-sa-extension.zip](https://github.com/user-attachments/files/17041977/rossum-sa-extension.zip)
=> Rossum SA ext: release version 0.14.0
