src/eslint-config-adeira/__tests__/__snapshots__/index.test.js.snap
src/eslint-config-adeira/ourRules.js
src/monorepo-scanner/src/scans/Babel.scan.js
src/monorepo-scanner/src/scans/Changelogs.DISABLED.js
src/monorepo-scanner/src/scans/NextjsApplications.scan.js
src/monorepo-scanner/src/scans/Workspaces.scan.js
src/monorepo-scanner/src/scans/WorkspacesDependencies.scan.js

See: https://github.com/jest-community/eslint-plugin-jest/issues/470#issuecomment-551989381

Eslint: re-enable 'jest/valid-title' rule

---

.flowconfig

I asked about this directly Flow developers from FB and they responded like this:
> We do that internally, and I would recommend you do it too!
Other developers also confirmed it works fine. Source: https://discordapp.com/channels/539606376339734558/539915538550226954/643493126035603496

Flow: move the whole 'node_modules' under declarations

---

package.json
scripts/publishNPMPackages.js
src/eslint-config-adeira/CHANGELOG.md
src/eslint-config-adeira/package.json
src/eslint-plugin-adeira/package.json
src/relay/package.json

These packages are needed by `@adeira/eslint-config`
Release `@adeira/eslint-config` version `0.2.0`

Release eslint-plugin-adeira

---

src/example-relay/__github__/.flowconfig

note that cloning https://github.com/adeira/relay-example repo and running flow still fails because of unit tests, I will address remaining issues in next MR

example-relay: Upgrade .flowconfig to set linting rules

---

src/graphql-global-id/README.md
src/graphql-global-id/package.json
src/graphql-global-id/src/GlobalID.d.ts

First steps forward TS support. I just hope NPM publisher includes `.d.ts` file automatically :-)

Typescript support for graphql-global-id

---

src/eslint-config-adeira/runner/__tests__/shouldLintAll.test.js
src/eslint-config-adeira/runner/shouldLintAll.js

Only .eslintignore in root works, so only lint all
if that file is changed. Ignore other files called .eslintigore

Fix shouldLintAll regex

---

src/relay/CHANGELOG.md
src/relay/package.json
src/relay/src/compiler/buildLanguagePlugin.js
src/relay/src/compiler/index.js
yarn.lock

This exposes public interface for changing the language plugin. Currently, people are mostly interested in 'javascript' or 'typescript' languages so I added support only for these two. Javascript is and will stay as a default.

Relay: expose language plugins interface

---

src/relay/bin/relay-compiler.js
src/relay/src/compiler/index.js

These options were added because of one legacy project which we don't have under control anymore. It was to enable multiple schemas in the same repository which is highly discouraged.

Relay CLI: remove include/exclude options

---

src/example-relay/package.json
src/relay/bin/fetch-schema.js
src/relay/bin/relay-compiler.js
src/relay/package.json

This feature was requested here https://github.com/adeira/universe/issues/189 and was greatly improved in Babel itself here https://github.com/babel/babel/pull/10778. It can however be annoying and sometimes difficult to do such modification so I changed my mind and I'd like to allow it after all. It's because this code where we require "upward" mode is necessary only for Universe development and should not affect users of our NPM package.

Relay: do not enforce project wide configuration

---

src/monorepo-shipit/config/__tests__/example-relay.test.js
src/monorepo-shipit/config/example-relay.js

Relay-example is not updated for last weeks because `.github` dir does not exist yet. 
We can always put it back but now it's better to keep repositories in sync.

shipit: Remove non-existing ".github" dir from "relay-example" config

---

src/graphql-global-id/package.json
src/graphql-global-id/src/GlobalID.d.ts
src/graphql-global-id/src/GlobalID.js
src/graphql-global-id/src/__tests__/GlobalID.test.js

Added `toGlobalId` to it's possible to create global ID not only in `GraphQLObjectType` field.

graphql-global-id: toGlobalId function added

---

src/relay/package.json
yarn.lock

This seems to be the easiest way how to migrate. Moreover, adeira/relay is not released as a stable library so we should be able to do this.

Use Relay experimental

---

scripts/jest/setupTests.js
src/relay/src/__tests__/RelayLogger.test.js

do not accidentally output calls to `console.groupCollapsed` when running unit tests:

relay: Mock "console.groupCollapsed" in unit tests

---

src/eslint-config-adeira/__tests__/__snapshots__/index.test.js.snap
src/eslint-config-adeira/ourRules.js

I would like to propose making `no-constant-condition` an error. There shouldn't be an use case for the following code:
```
if (true) {
stuff();
}
```
and constant conditions will remain allowed in loops thanks to `{ checkLoops: false }`.
This type of mistake can occur in code when a developer wants to quickly enable/disable particular branch of code, e.g.:
```
if (isTurnedOn() && false) {
doStuff();
}
```
Such a practice should be discouraged, leading me to this suggestion.

eslint-config: change "no-constant-condition" from warning to error

---

src/example-relay/__github__/.flowconfig
src/example-relay/__github__/flow-typed/npm/next_v7.x.x.js
src/example-relay/src/pages/_document.js

I would like to move forward with fixing relay example app - https://github.com/adeira/relay-example/runs/386995819
- Meanwhile, I opened this MR on flow-typed: https://github.com/flow-typed/flow-typed/pull/3699

example-relay: Add flow definitions for next

---

package.json
src/eslint-config-adeira/CHANGELOG.md
src/eslint-config-adeira/README.md
src/eslint-config-adeira/package.json

- update readme
- release `@adeira/eslint-config` 1.1.0 with `--no-warnings`

Release @adeira/eslint-config 1.1.0

---

src/example-relay/__github__/jest.config.js
src/example-relay/jest.config.js
src/monorepo-shipit/config/__tests__/example-relay.test.js
src/monorepo-shipit/config/example-relay.js

There was a logical error: you cannot try to ship some file and then strip it from the shipping process. I am not sure we actually support such file replacement. This could be (in theory) fairly simple to fix by reordering the filters.

Relay example: fix misconfigured Shipit

---

src/babel-preset-adeira/package.json
src/eslint-config-adeira/package.json
src/flow-bin/package.json
src/monorepo-builder/package.json
src/monorepo-npm-publisher/package.json
src/monorepo-scanner/package.json
src/monorepo-shipit/package.json
src/monorepo-utils/package.json
src/monorepo-utils/src/getWorkspaceDependencies.js
src/relay/package.json

The output of this call was changed in 1.22.0.
This change will make it work with new format and older formats

utils: Handle output from yarn workspaces info --json

---

src/example-relay/package.json
src/fetch/CHANGELOG.md
src/fetch/package.json
src/relay/package.json
src/vault2env/package.json

Version 1.0.0 actually sends @adeira/fetch (+https://github.com/kiwicom/fetch; 1)

Release @adeira/fetch 1.0.1

---

src/monorepo-utils/README.md
src/monorepo-utils/src/index.js

I would like to expose `getChangedFiles` from `@adeira/monorepo-utils` as we need exactly what this function does for custom CI script - deciding whether recompile stylus files scattered across multiple workspaces.

monorepo-utils: Expose "getChangedFiles" function

---

src/monorepo-utils/README.md

I would call it stable 🙂 
(at most the whole package itself is unstable as long the version is 0.x)

monorepo-utils: update readme to contain more info about Git utils

---

src/monorepo-npm-publisher/CHANGELOG.md
src/monorepo-npm-publisher/src/transformFileVariants.js

Use rootMode upwards to apply the babel config from the project
using this package, rather than force the @adeira/babel-preset
closes #196

npm-publisher: Use projects babel config

---

src/monorepo-utils/src/TestsRunner.js

Currenlty it was logging UTC, even if you had another
timezone in process.env.TZ

monorepo-utils: Correctly log timezone

---

src/graphql-global-id/package.json

Closes: https://github.com/adeira/universe/issues/485

@adeira/graphql-global-id: add @babel/runtime into dependencies

---

package.json
src/__flowtests__/lints/sketchy-null.js
src/__flowtests__/lints/sketchy-number.js
src/example-relay/package.json
src/fetch/src/ResponseError.js
src/fetch/src/__tests__/ResponseError.test.js
src/graphql-global-id/src/__tests__/GlobalID.test.js
src/monorepo-utils/src/__flowtests__/glob.js
src/relay/src/__flowtests__/LocalQueryRenderer.js
src/relay/src/__flowtests__/QueryRenderer.js
src/relay/src/__flowtests__/mutations.js
src/relay/src/__tests__/createPaginationContainer.test.js
src/relay/src/__tests__/createRefetchContainer.test.js
src/relay/src/__tests__/helpers.handleData.test.js
src/relay/src/fetchers/__flowtests__/createNetworkFetcher.js
yarn.lock

This change also relocates error suppression comments to the primary locations which is a first step towards new and more specific suppressions, see: https://medium.com/flow-type/making-flow-error-suppressions-more-specific-280aa4e3c95c

Upgrade Flow to the latest version ^0.121.0

---

src/eslint-plugin-adeira/package.json
src/fetch/package.json
src/flow-bin/package.json
src/graphql-bc-checker/package.json
src/js/package.json
src/logger/package.json
src/monorepo-npm-publisher/package.json
src/monorepo-scanner/src/scans/NpmPackages.scan.js
src/monorepo-utils/package.json
src/relay-runtime/package.json
src/relay-utils/package.json
src/relay/package.json
src/signed-source/package.json
src/test-utils/package.json

I was considering to stop using it but that would blow up the NPM size significantly. Moreover it's not that simple to opt-out from it. So instead, we should require it everywhere for public NPM packages (via our Scanner).
Closes: https://github.com/adeira/universe/issues/526

Require @babel/runtime for public NPM packages

---

src/graphql-global-id/CHANGELOG.md
src/graphql-global-id/README.md
src/graphql-global-id/package.json
src/graphql-global-id/src/GlobalID.d.ts
src/graphql-global-id/src/GlobalID.js
src/graphql-global-id/src/__tests__/GlobalID.test.js

Preparation for stable release.

GraphQL ID: rename `__isTypeOf` to `isTypeOf`

---

src/test-utils/package.json
src/test-utils/src/__tests__/evaluateGraphQLResolver.test.js
src/test-utils/src/evaluateGraphQLResolver.js
src/test-utils/src/index.js

Fields without explicit resolver are supported now.
It also calls `serialize` method if the field has one (scalars does) so invalid inputs can be tested.

Improved evaluateGraphQLResolver

---

src/relay-runtime/package.json
src/relay-runtime/src/RelayLogger.js
src/relay-runtime/src/RelayNetworkTypes.js
src/relay-runtime/src/__tests__/RelayLogger.node.test.js
src/relay-runtime/src/__tests__/RelayLogger.test.js
src/relay-utils/package.json
src/relay/package.json

This change better displays responses which are successful only partially. Otherwise, these errors can be really well hidden and it's easy to overlook them.

Relay logger: show partial responses with errors

---

src/relay/src/mutations.js

Our flow types are better than relay's at them moment.
So let's stay with ours

relay: Suppress flow error in mutations.js

---

src/relay-runtime/index.js
src/relay/src/LocalQueryRenderer.js
src/relay/src/QueryRenderer.js
src/relay/src/__flowtests__/CustomQueryRenderer.js
src/relay/src/__flowtests__/Disposable.js
src/relay/src/createRefetchContainer.js
src/relay/src/fetchQuery.js
src/relay/src/hooks/__flowtests__/useMutation.js
src/relay/src/hooks/useMutation.js
src/relay/src/index.js
src/relay/src/mutations.js
src/relay/src/readInlineData.js
src/relay/src/requestSubscription.js
src/relay/src/types.flow.js

Move disposable and GraphQLTaggedNode types to @adeira/relay-runtime

relay: Use disposable type from relay-runtime

---

package.json
yarn.lock

When we remove flow-typed as dependency we can remove prettier
from resolutions. Flow typed could be used through npx
or installed globally

Remove flow typed as dependency

---

src/example-relay/package.json
src/example-relay/src/mutations/FadeIn.js
src/example-relay/src/mutations/LocationsList.js
src/example-relay/src/mutations/RangeAdd/LocationsForm.js
src/example-relay/src/mutations/RangeAdd/__generated__/LocationsFormMutation.graphql.js
src/example-relay/src/pages/_app.js
src/relay-utils/package.json
src/relay/CHANGELOG.md
src/relay/package.json
src/relay/src/createEnvironment.js
yarn.lock

Removing the one we had in createEnvironment since it prevents usage of new directives like `@prependEdge`. Consumer can still add his override handlerProvider if needed, but using the one from `react-relay` by default makes more sense. 
Release `@adeira/relay` 2.0.1.
Use `@prependEdge` in example relay

Remove handler provider from createEnvironment

---

src/example-relay/package.json
src/relay-utils/package.json
src/relay/package.json
src/relay/src/fetchQuery.js

This should enable passing generated types which are now incompatible with mixed, e.g.:
```
export type fetchCreditsQuery = {|
variables: fetchCreditsQueryVariables,
response: fetchCreditsQueryResponse,
|};
// ... later:
const response = await fetchQuery<fetchCreditsQuery>(env, query, variables);
```

Improve relay types

---

src/example-relay/__github__/.flowconfig

This option has been removed from Flow, see: 93d01d89c8337dbd85c09a677a613e435180513f

Relay example: remove `dynamic-export` from .flowconfig

---

package.json
yarn.lock

I tested it without it and it seems to be working fine. I don't even remember why was it there. Seems like we no longer have this problem (?).

Dependencies: remove Eslint resolution

---

src/docs/docusaurus.config.js

`themeConfig.navbar.links` has been renamed as `themeConfig.navbar.items`

Docs: Fix config

---

src/relay/CHANGELOG.md
src/relay/package.json
src/relay/src/createRequestHandler.js
src/relay/src/fetchers/createNetworkFetcher.js
yarn.lock

This partially reverts 5acc6c1d5a5eb0eb8e09c902b5d3ba3b92b28ec7 - turned out it's a bit tricky to implement it properly to support even IE 11. Will try again somewhere down the road.

Relay: partially revert abort controller

---

src/graphql-global-id/CHANGELOG.md
src/graphql-global-id/package.json
src/graphql-global-id/src/index.js

I'm gonna need it for `graphql-relay-fauna` package

Global ID: Export Encoder

---

.flowconfig
src/flow-bin/bin/migrate/types-first.js

I incorrectly changed the command in af7c259283d1d1cc2aa16ceeb69ced2f485300c9 (it accepts the whole folders and not files). It worked as well but it was too slow.

Flow: fix types-first migration command

---

src/example-relay/package.json
src/example-relay/src/pages/_app.js
yarn.lock

With the new version of Chrome extension the setup code is not needed anymore.

Relay example: Remove relay-devtools

---

src/sx/README.md

Flow type from Readme example removed to make it more simple.
Added import from `next/document` to make the example copy&paste ready.

SX: Fix example in Readme

---

src/example-relay/src/components/Navbar.js

Next.js was complaining about invalid anchor usage (which was resulting in anchors without HREF).

Relay example: fix anchor warnings

---

src/sx/src/__tests__/__snapshots__/renderStatic.test.js.snap
src/sx/src/__tests__/fixtures/media-queries-nested-pseudo.json
src/sx/src/__tests__/renderStatic.test.js

This way we can not only text the resulting CSS but also the resulting HTML classes. I deleted some tests which were a bit redundant thanks to this.

SX: improve fixture tests

---

src/example-relay/package.json
src/example-relay/src/Homepage/index.js
src/example-relay/src/Homepage/locations/Location.js
src/example-relay/src/Homepage/locations/LocationsPaginated.js
src/example-relay/src/Homepage/locations/LocationsPaginatedBidirectional.js
src/example-relay/src/Homepage/locations/LocationsPaginatedRefetch.js
src/example-relay/src/LocalForm/index.js
src/example-relay/src/components/Button.js
src/example-relay/src/components/Header.js
src/example-relay/src/components/Heading.js
src/example-relay/src/components/Navbar.js
src/example-relay/src/components/Select.js
src/example-relay/src/components/Text.js
src/example-relay/src/components/TextInput.js
src/example-relay/src/components/breakpoints.js
src/example-relay/src/mutations/LocationsList.js
src/example-relay/src/mutations/RangeAdd/LocationsForm.js
src/example-relay/src/mutations/RangeAdd/__tests__/RangeAdd.test.js
src/example-relay/src/pages/_app.js
src/example-relay/src/pages/mutations/range-add.js
src/example-relay/src/styles/app.css
src/monorepo-scanner/src/scans/WorkspacesDependencies.scan.js
yarn.lock

- Currently deactivate client side routing, since it doesn't work with sx
- Next up: remove gromment-icons, so we can remove styled-components

example: Replace grommet with sx styled components

---

src/sx/src/create.js
src/sx/src/css-renderers/__tests__/renderAtomicClass.test.js
src/sx/src/css-renderers/__tests__/renderAtomicClasses.test.js
src/sx/src/css-renderers/__tests__/renderMediaQuery.test.js
src/sx/src/css-renderers/renderAtomicClass.js
src/sx/src/css-renderers/renderAtomicClasses.js
src/sx/src/css-renderers/renderMediaQuery.js
src/sx/src/renderStatic.js
src/sx/src/styleBuffer.js

This way we can reuse it when working with the runtime styles.

SX: decouple CSS rendering logic

---

src/babel-preset-adeira/README.md

- Mention that js-esm is necessary for codes-splitting to work

babel-preset: Add note about code-splitting

---

src/monorepo-shipit/config/__tests__/docs-adeira-dev.test.js
src/monorepo-shipit/config/__tests__/example-relay.test.js
src/monorepo-shipit/config/__tests__/monorepo-shipit.test.js
src/monorepo-shipit/config/__tests__/sx.test.js
src/monorepo-shipit/src/ShipitConfig.js
src/monorepo-shipit/src/__tests__/RepoGit.commitPatch.test.js
src/monorepo-shipit/src/__tests__/ShipitConfig.test.js
src/monorepo-shipit/src/__tests__/__snapshots__/ShipitConfig.test.js.snap
src/monorepo-shipit/src/utils/createMockChangeset.js
src/monorepo-shipit/src/utils/createMockDiff.js

I think it doesn't make sense to ship these files outside of monorepo so I am adding them to the default filter. It can be eventually made configurable if needed.

Shipit: strip BUILD files by default

---

src/eslint-config-adeira/CHANGELOG.md
src/eslint-config-adeira/__tests__/__snapshots__/index.test.js.snap
src/eslint-config-adeira/getCommonConfig.js
src/js/CHANGELOG.md

This seems to be very project specific and unused in Adeira universe.

Eslint config: remove '__' global

---

src/example-relay/package.json
src/sx/src/StyleCollector.js
src/sx/src/StyleCollectorAtNode.js
src/sx/src/StyleCollectorNode.js
src/sx/src/StyleCollectorPseudoNode.js
src/sx/src/__tests__/StyleCollector.test.js
src/sx/src/__tests__/StyleCollectorAtNode.test.js
src/sx/src/__tests__/StyleCollectorPseudoNode.test.js
src/sx/src/__tests__/__snapshots__/renderPageWithSX.test.js.snap
src/sx/src/__tests__/fixtures/pseudo-classes-multiple.json
src/sx/src/__tests__/renderPageWithSX.test.js
yarn.lock

I broke this here: https://github.com/adeira/universe/commit/692f3e1c0c2383663bf39de3eb087df0b2022f43 (Relay example was using the old SX version and I incorrectly thought it works fine)
The style buffer must be initialized only once and reset only when needed (explicitly) because it must remember the styles across the whole application. Moreover, the collected styles must be merged in the style buffer rather than adding them to the set.
Test plan: make sure the relay example still works as expected.

SX: fix style buffer collecting and resetting

---

LICENSE

I need a link to the license of this repository so this placeholder should serve the purpose (we have different licences per project in the monorepo).

Add root license file

---

src/babel-plugin-transform-sx-tailwind/package.json
src/babel-plugin-transform-sx-tailwind/src/__tests__/fixtures/nested/code.js
src/babel-plugin-transform-sx-tailwind/src/__tests__/fixtures/nested/output.js
src/babel-plugin-transform-sx-tailwind/src/index.js

This PR fixes bug when `tailwind` was used in nested elements. Styles of children elements were merged with styles of parents.

SXT Babel: Nested usage fix

---

src/sx-tailwind-website/.gitignore
src/sx-tailwind-website/__github__/.github/workflows/continuous-integration.yml
src/sx-tailwind-website/package.json
yarn.lock

Strangely the exported project builds OK on my machine or in Github Action but fails on Vercel.
So far a workaround is to use `next export` and don't use predefined Next.js settings in Vercel.

SXT Website: Build fix

---

src/example-relay/package.json
src/sx-tailwind-website/package.json
src/sx-tailwind/package.json
src/sx/README.md
src/sx/__flowtests__/css-properties.js
src/sx/__flowtests__/sx.js
src/sx/package.json
src/sx/src/__tests__/SxDomTests.test.js
src/sx/src/__tests__/__snapshots__/fixtures.test.js.snap
src/sx/src/__tests__/fixtures.test.js
src/sx/src/__tests__/fixtures/pseudo-classes-nested-2.js
src/sx/src/__tests__/fixtures/pseudo-elements-2.js
src/sx/src/__tests__/fixtures/pseudo-elements.js
src/sx/src/__tests__/renderPageWithSX.test.js
src/sx/src/__tests__/transformValue.test.js
src/sx/src/renderPageWithSX.js
src/sx/src/transformValue.js

- Render generated css with dangerouslySetInnerHtml
It is necessary to specify the quoutes of the content, since
usage with a counter will not work if we automatically add the qoute.

sx: Remove auto adding of quotes in content

---

src/sx/src/StyleCollectorNode.js
src/sx/src/__tests__/StyleCollector.test.js
src/sx/src/__tests__/StyleCollectorAtNode.test.js
src/sx/src/__tests__/StyleCollectorNode.test.js
src/sx/src/__tests__/StyleCollectorPseudoNode.test.js
src/sx/src/__tests__/__snapshots__/fixtures.test.js.snap
src/sx/src/__tests__/create.test.js
src/sx/src/__tests__/fixtures/simple-transforms.js
src/sx/src/__tests__/renderPageWithSX.test.js

Previously, we were hashing raw style names and values which could result in duplicated CSS classes. We should hash already transformed style names and values instead. This commit fixes it.

SX: hash already transformed values

---

src/babel-plugin-transform-sx-tailwind/package.json
src/babel-plugin-transform-sx-tailwind/src/index.js
src/sx-tailwind-website/.babelrc.js
src/sx-tailwind-website/.eslintrc.js
src/sx-tailwind-website/__github__/.babelrc.js
src/sx-tailwind-website/package.json
src/sx-tailwind-website/src/Documentation/index.js
src/sx-tailwind-website/src/TailwindCss/Alerts.js
src/sx-tailwind-website/src/TailwindCss/Buttons.js
src/sx-tailwind-website/src/TailwindCss/Cards.js
src/sx-tailwind-website/src/TailwindCss/Forms.js
src/sx-tailwind-website/src/components/SyntaxHighlighter.js
src/sx-tailwind-website/src/pages/_app.js
yarn.lock

This enables usage of the `babel-plugin-transform-sx-tailwind` within monorepo. Local deps are just symlinked which can be an issue if a transpilation must be done.
It also adds styles collector reset when a new file is processed, this causes crashes during build.

SXT Babel: Enable usage within monorepo

---

src/monorepo-shipit/config/__tests__/adeira-dev.test.js
src/monorepo-shipit/config/__tests__/example-relay.test.js
src/monorepo-shipit/config/__tests__/sx-tailwind-website.test.js
src/monorepo-shipit/config/__tests__/testExportedPaths.js
src/monorepo-shipit/config/sx-tailwind-website.js
src/sx-tailwind-website/__github__/babel.config.js

Shipit doesn't understand file replacing so it has to be done differently. Moreover, I think 'babel.config.js' is the right choice here (just like in Relay Example project).
Note: manual synchronization might be needed after this because seems like the exported repo is out of sync

Shipit: fix 'sx-tailwind-website' Babel config export

---

src/babel-plugin-transform-sx-tailwind/src/index.js

This should be needed only for Universe and doesn't work well on OSS. It should fix the following error:
> Error: Reentrant plugin detected trying to load "/adeira/sx-tailwind-website/node_modules/@adeira/babel-plugin-transform-sx-tailwind/src/index.js". This module is not ignored and is trying to load itself while compiling itself, leading to a dependency cycle. We recommend adding it to your "ignore" list in your babelrc, or to a .babelignore.

SX Babel plugin: disable Babel Register call for OSS

---

src/babel-plugin-transform-sx-tailwind/package.json
src/babel-plugin-transform-sx-tailwind/src/index.js
src/monorepo-npm-publisher/README.md
src/monorepo-npm-publisher/src/transformFileVariants.js
src/sx-tailwind-website/package.json

This should remove the `@babel/register` from NPM version since it's needed only for Adeira Universe monorepo and it's problematic when exported outside of the repo.
I tried to use the modified NPM output in SX Tailwind website and it worked well. It also works well under Universe workspace. This issue should be eventually solved by design with the migration to Bazel.

SX tailwind: remove '@babel/register' call from NPM

---

src/sx/src/__tests__/colorNormalizer.test.js
src/sx/src/colorNormalizer.js

This commit introduces and improved detection of colors. Specifically, it understands hexadecimal RGB syntaxes with alpha channel as well as rgb(), rgba(), hsl() and hsla(). The functional syntaxes are simplified (no whitespace syntax support, weak floats values, no further validation like mixing percentages and numbers). This can be improved later when needed.
We need to improve this `isColor` function because some parts of the SX system rely on this detection (for example expansion of shorthand properties where we need to detect what is a color in `background` property).
I am also considering a new package `@adeira/css-color` because it might be quite handly when we master this.

SX: improve color detection to support rgba() and hsla()

---

src/example-relay/src/Homepage/index.js
src/example-relay/src/components/breakpoints.js

Around 1300px, it would generate a 4th empty column.
Now it will use 3 columns on view width > 992px

relay-example: Specify grid colums on desktop size

---

src/sx/README.md
src/sx/src/StyleCollector.js
src/sx/src/__tests__/StyleCollector.test.js
src/sx/src/__tests__/SxDomTests.test.js
src/sx/src/__tests__/expandShorthandProperties.test.js
src/sx/src/__tests__/renderPageWithSX.test.js
src/sx/src/expandShorthandProperties.js

Purpose of this change is to expand shorthand CSS properties which could cause conflics when defined together. Imagine the following example:
```
const styles = sx.create({
primary: { marginTop: '10px' },
button: { margin: 0 },
});
```
It could generate the following CSS:
```
.c0 { margin-top: 10px }
.c1 { margin: 0px }
```
That would be a tricky situation because CSS specificity depends on the CSS definition order and therefore the top margin would be always overwritten when used together. Instead, we expand the shorthand properties into something like this:
```
.c0 { margin-top: 10px }   << primary
.c1 { margin-top: 0px }    << button
.c2 { margin-right: 0px }
.c3 { margin-bottom: 0px }
.c4 { margin-left: 0px }
```
This way SX is not dependent on the CSS rules insertion order but rather …

SX: expand shorthand properties

---

src/babel-plugin-transform-sx-tailwind/package.json
src/babel-plugin-transform-sx-tailwind/src/TemplateLiteralHandler.js
src/babel-plugin-transform-sx-tailwind/src/__tests__/fixtures/template-literal-condition/code.js
src/babel-plugin-transform-sx-tailwind/src/__tests__/fixtures/template-literal-condition/output.js
src/babel-plugin-transform-sx-tailwind/src/__tests__/fixtures/template-literal/code.js
src/babel-plugin-transform-sx-tailwind/src/__tests__/fixtures/template-literal/output.js
src/babel-plugin-transform-sx-tailwind/src/index.js
src/sx-tailwind-website/package.json
src/sx-tailwind-website/src/components/Sidebar.js

`tailwind` method can now contain template literals with conditional expressions

SXT Babel: Template literals support

---

src/example-relay/public/reset.css
src/example-relay/src/pages/_document.js
src/sx/README.md
src/sx/src/__tests__/SxDomTests.test.js
src/sx/src/renderPageWithSX.js

We couldn't decide whether to use CSS reset or normalization and concluded that we should leave this decision for the user.

SX: remove CSS reset

---

src/example-relay/src/components/Navbar.js
src/example-relay/src/styles/nprogress.css
src/sx-tailwind-website/src/components/Sidebar.js
src/sx/README.md
src/sx/src/StyleCollector.js
src/sx/src/StyleCollectorAtNode.js
src/sx/src/StyleCollectorNode.js
src/sx/src/StyleCollectorNodeInterface.js
src/sx/src/StyleCollectorPseudoNode.js
src/sx/src/__tests__/StyleCollectorAtNode.test.js
src/sx/src/__tests__/StyleCollectorNode.test.js
src/sx/src/__tests__/StyleCollectorPseudoNode.test.js
src/sx/src/__tests__/expandShorthandProperties.test.js
src/sx/src/create.js
src/sx/src/injectRuntimeStyles.js

Runtime styles should be now working. You can test it by running Relay Example or SX Tailwind Website and try to go from page to page. You should see that the styles work as expected without the need to SSR the styles.
Closes: https://github.com/adeira/universe/issues/1012
TODO:

SX: add support for runtime styles

---

src/eslint-config-adeira/CHANGELOG.md
src/eslint-config-adeira/__tests__/__snapshots__/index.test.js.snap
src/eslint-config-adeira/ourRules.js

Turning this eslint rule off since flow doesn't work with non-string literal
property keys, https://github.com/facebook/flow/issues/380.

eslint-config: Turn off eslint rule no-useless-computed-key

---

src/sx/src/css-properties/__generated__/AllCSSPropertyTypes.js
src/sx/src/css-properties/generateFlowTypes.js

This should help writing a better code. Obsolete and nonstandard properties will still work but user has to explicitly flow-ignore them and therefore acknowledging they are doing something unusual.

SX: do not generate Flow types for obsolete and nonstandard properties

---

src/eslint-runner/reporter.js

The last number of the total was cut behind the cursor.
Now you can see the entire total.
Before
After

eslint-runner: Add space after total in progressbar

---

src/adeira.dev/.babelrc.js
src/adeira.dev/__github__/babel.config.js
src/adeira.dev/package.json
src/monorepo-shipit/config/__tests__/adeira-dev.test.js
src/monorepo-shipit/config/adeira-dev.js

The build was failing after we added the new JSX transform.
This should fix the failing build

adeira.dev: Add babel.config.js to adeira.dev project

---

src/eslint-config-adeira/package.json
src/eslint-plugin-sx/package.json
src/eslint-plugin-sx/src/rules/__tests__/__snapshots__/no-unused-stylesheet.test.js.snap
src/eslint-plugin-sx/src/rules/__tests__/__snapshots__/normalizeIndent.test.js.snap
src/eslint-plugin-sx/src/rules/__tests__/fixtures/no-unused-stylesheet/invalid/sx-multiple-definitions.js
src/eslint-plugin-sx/src/rules/__tests__/fixtures/no-unused-stylesheet/invalid/unknown-stylesheet.js
src/eslint-plugin-sx/src/rules/__tests__/no-unused-stylesheet.test.js
src/eslint-plugin-sx/src/rules/__tests__/normalizeIndent.js
src/eslint-plugin-sx/src/rules/__tests__/normalizeIndent.test.js
src/eslint-plugin-sx/src/rules/no-unused-stylesheet.js

Previously, we were reporting the errors with 'Program' node which resulted in the whole file being marked as errored. That's a bad practice since you need to go and search for the actual error location. This commit improves the behavior by reporting the errors with relevant nodes. This results in much better error location reporting.

Eslint SX: improve error nodes location

---

src/css-colors/src/isColor.js
src/sx/src/__tests__/expandShorthandProperties.test.js
src/sx/src/expandShorthandProperties.js

It was crashing becuase we were trying to split number into chunks. The type of the value was not accurate (`any`) so Flow could not catch it.

SX: fix shorthand expansion of `flex:1`

---

src/eslint-plugin-sx/package.json
src/example-relay/package.json
src/sx-tailwind-website/package.json
src/sx-tailwind/package.json
src/sx/package.json

I found out runtime styles for animations does not work here:
https://sx-tailwind.adeira.dev/tailwind-css/animations
Release of a new version should fix this because the website works OK in the monorepo.

SX: Release version 0.20.0

---

src/eslint-runner/package.json

There is a minor fix which I think is worth releasing since no other changes are planned (it could take a while before we release a new version naturally).

Eslint runner: release version 1.0.2

---

src/eslint-config-adeira/__tests__/__snapshots__/index.test.js.snap
src/eslint-config-adeira/ourRules.js
src/eslint-config-adeira/package.json
src/eslint-plugin-adeira/README.md
src/eslint-plugin-adeira/package.json
src/eslint-plugin-adeira/src/index.js
src/eslint-plugin-adeira/src/rules/__tests__/flow-use-readonly-spread.test.js
src/eslint-plugin-adeira/src/rules/flow-use-readonly-spread.js
src/flow-types-eslint/.eslintrc.js
src/flow-types-eslint/src/index.js
src/flow-types-eslint/src/types/GenericTypeAnnotation.js
src/flow-types-eslint/src/types/NumberLiteralTypeAnnotation.js
src/flow-types-eslint/src/types/ObjectTypeAnnotation.js
src/flow-types-eslint/src/types/ObjectTypeProperty.js
src/flow-types-eslint/src/types/ObjectTypeSpreadProperty.js
src/flow-types-eslint/src/types/StringLiteralTypeAnnotation.js
src/flow-types-eslint/src/types/TypeAlias.js
src/flow-types-eslint/src/types/Variance.js

The purpose of this rule is to check types inside `flow-types-eslint` package to prevent accidental wrong Flow types breaking readonly-ness. See this example for more details: https://flow.org/try/#0C4TwDgpgBAkgcgewCbQLxQN4B8BQUoDUokAXFAM7ABOAlgHYDmANHoVQIaMRkDadArgFsARhCpMoAkWIC6LfATDsqEOsDICANpqhZYiFCywBfANw4cAektQAsv0pRRUACQAlCOyQB5OppAAhDjE0DAoajQAZjRiUOjunj5+IAA82KwAdFnwyBDyhHTsgtwU1PTMOCYAfOY4AMYIdI4AHmRhqsBRMVRxmIXFJABEgxIhQyNQHFwkPACMTABMclBKKmokWprGFs0ZIb0A5ADKABYI-JpIkgjATtAA7rTA7MKaEAEH5rv9aFDHZxcrnQbncoI8aM9Xu9PjggA

Eslint: add new opt-in rule 'flow-use-readonly-spread'

---

src/babel-plugin-transform-sx-tailwind/package.json
src/babel-plugin-transform-sx-tailwind/src/__tests__/__snapshots__/index.test.js.snap
src/babel-plugin-transform-sx-tailwind/src/__tests__/fixtures/error/invalid-utility-class.js
src/babel-plugin-transform-sx-tailwind/src/__tests__/index.test.js
src/babel-plugin-transform-sx-tailwind/src/getCssDeclarations.js
src/sx-tailwind-website/package.json
yarn.lock

SXT Babel: Better DX for invalid utility class name

---

src/sx-tailwind-website/package.json
yarn.lock

No idea why, but the build of exported project is failing with `Cannot find module '@babel/core'`:
https://vercel.com/adeira/sx-tailwind-website/a8e94qgbq

SXT Website: Add babel/core

---

src/graphql-result-size/package.json
src/monorepo-shipit/config/__tests__/graphql-result-size.test.js
src/monorepo-shipit/config/graphql-result-size.js
yarn.lock

This project is no longer maintained nor does it have a good use-case. However, I consider it an important part in my GraphQL research so I'd like to archive it following these steps:
1. open-source it via Shipit here: https://github.com/adeira/graphql-result-size
2. archive the GitHub repository
3. remove the Shipit export

1/n: archive 'graphql-result-size'

---

.github/.kodiak.toml
.github/dependabot.yml

Currently, we are using `dependabot-preview` which supports automatic merges but it's not configurable anymore. This commit migrates it to native GitHub Dependabot which allows us to configure other automated updates like GitHub actions. Automatic merging is done via Kodiak.
Closes: https://github.com/adeira/universe/issues/932

CI: explicitly setup Dependabot

---

src/flow-config-parser/package.json
src/flow-config-parser/src/__tests__/parse.test.js
src/monorepo-scanner/src/scans/YarnLock.scan.js

If we forget to upgrade a dependency in one of our packages
We might get an old version from npm installed instead.
This should fail the CI if we don't keep our deps up to date

scanner: Test that we have no @adeira package in yarn.lock

---

src/murmur-hash/README.md
src/murmur-hash/src/murmurHash.d.ts

TS definitions moved to DefinitelyTyped (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49865) since we cannot maintain/test them properly. Please review that PR as well.
I'd like to release a stable version once we merge the TS types PR.

Cleanup '@adeira/murmur-hash' in preparation for stable release

---

src/eslint-config-adeira/package.json
src/eslint-plugin-adeira/BUILD.bazel
src/eslint-plugin-adeira/package.json
src/eslint-plugin-adeira/src/rules/__tests__/graphql-require-object-description.test.js
src/eslint-plugin-adeira/src/rules/__tests__/no-duplicate-import-type-import.test.js
src/eslint-plugin-adeira/src/rules/__tests__/no-internal-flow-type.test.js
src/eslint-plugin-adeira/src/rules/__tests__/relay-import-no-values.test.js
src/eslint-plugin-adeira/src/rules/__tests__/relay-import-type-must-exist.test.js
src/eslint-plugin-adeira/src/rules/__tests__/valid-test-folder.test.js

`babel-eslint` is deprecated, see: https://github.com/adeira/universe/issues/941

Babel plugin Adeira: use '@babel/eslint-parser'

---

.github/workflows/continuous-integration-rust.yml

To make sure the code works for both Apple and Linux platforms. CI for each platform is slightly different: for Apple we run only tests to make sure it works for local development whereas on Linux we run Clippy, tests and release build (the assumption is that production uses Linux). This also saves some CI time on Macos machine.

CI: setup Rust cross compilation (Apple, Linux)

---

src/monorepo-shipit/src/filters/__tests__/__snapshots__/moveDirectories.test.js.snap
src/monorepo-shipit/src/filters/__tests__/_esc.test.js
src/monorepo-shipit/src/filters/__tests__/fixtures/new-file-complex.patch
src/monorepo-shipit/src/filters/__tests__/moveDirectories.test.js
src/monorepo-shipit/src/filters/_esc.js
src/monorepo-shipit/src/filters/conditionalLines.js
src/monorepo-shipit/src/filters/moveDirectories.js

Previously, Shipit was not able to handle complex file paths such as the following correctly:
```text
Images.xcassets/Logo (no background).imageset/Contents.json
```
This commit should fix the issue allowing it to work again for these complex paths.

Shipit: fix 'moveDirectories' filter escaping

---

.github/workflows/continuous-integration-javascript.yml
src/relay-runtime/src/RelayEagerLogger.js
src/relay-runtime/src/RelayLazyLogger.js
src/relay-runtime/src/__tests__/RelayEagerLogger.test.js

Somehow, we merged a PR with Relay 10.1.1 without catching the Flow errors on CI. Here is what _I think_ happened:
- the PR changed only `package.json` files which we correctly written into `.flow.saved_state_file_changes`
- we started the server in a lazy FS mode which initialized with 0 changed files (also correct)
- we called `flow force-recheck` for these `package.json` files which however doesn't refocus well enough and doesn't have any effect on the typechecking -> still 0 changed files
- Flow said "OK" even though there were errors
This workflow usually works for JS files but it doesn't work when no JS files changed (in the previous scenario only JSON files changed).
I created a TODO for myself to improve the workflow, possibly to remove the lazy mode completely (or run Flow …

Relay runtime: fix broken Flow types

---

src/example-relay/package.json
src/relay-runtime/package.json
src/relay-utils/package.json
src/relay/package.json

This release includes support for the latest Relay 10.1.2.

Release '@adeira/relay-runtime' version 0.19.0

---

src/css-colors/CHANGELOG.md
src/css-colors/README.md
src/css-colors/package.json
src/css-colors/src/__tests__/calculateBrightness.test.js
src/css-colors/src/__tests__/isBright.test.js
src/css-colors/src/__tests__/isDark.test.js
src/css-colors/src/calculateBrightness.js
src/css-colors/src/index.js
src/css-colors/src/isBright.js
src/css-colors/src/isDark.js
src/sx/package.json

It would be also nice to have a utility for HEX <-> RGB array, see: https://github.com/chromium/chromium/blob/15aa6bb80864a6dd89c25313dfd2839c6055724e/third_party/google_input_tools/third_party/closure_library/closure/goog/color/color.js#L158-L193

CSS colors: add `isBright` and `isDark` functions

---

src/ya-comiste-rust/Cargo.lock
src/ya-comiste-rust/server/Cargo.toml
src/ya-comiste-rust/server/src/main.rs
src/ya-comiste-rust/server/src/tests.rs

Purpose of these changes it to get rid of `juniper_warp` dependency and get more control over the accepted request methods (only POST with JSON body and POST with multipart body for GraphQL queries with file upload).

YCR: drop `juniper_warp` dependency

---

src/ya-comiste-rust/Cargo.lock
src/ya-comiste-rust/server/Cargo.toml

Previously, we used `juniper_warp` which didn't work with the latest `warp` version. However, that's no longer the case and there is no reason to use Juniper master.

YCR: use fixed Juniper version

---

src/sx/index.js
src/sx/src/__tests__/composability.test.js

It's useful to make the second `sx(…)` argument optional because the style overwriting property might be quite often nullable as well (styles might need overwriting only sometimes).

SX: handle nullable composable styles gracefully

---

src/ya-comiste-meta/schema.graphql
src/ya-comiste-rust/Cargo.lock
src/ya-comiste-rust/server/Cargo.toml
src/ya-comiste-rust/server/src/auth/error.rs
src/ya-comiste-rust/server/src/auth/mod.rs
src/ya-comiste-rust/server/src/auth/session.rs
src/ya-comiste-rust/server/src/auth/users/mod.rs
src/ya-comiste-rust/server/src/graphql_schema.rs

Last missing piece for the session management. Session tokens are essentially long-time passwords and we should store them securely as well. This commits tries to find a balance between security and performance since we have to work with the hashes per API request (PBKDF2 with many iterations is too slow and unnecessary in our case).

YCR: hash session tokens

---

.github/CODEOWNERS
src/monorepo-scanner/src/scans/Codeowners.scan.js

There are 2 main changes:
- we are using GH team instead of explicit nicknames
- every team member of `@adeira/devs` can approve everything like it was before but, additionally, `@adeira-github-bot` can approve the projects with only one main maintainer (to prevent situations like this one: https://github.com/adeira/universe/pull/1600)
This commit partially reverts a2b7a0b3d804ef478ec6655235d5ba190edf5e50

Update CODEOWNERS with core maintainers team

---

src/ya-comiste-meta/schema.graphql
src/ya-comiste-rust/server/src/auth/api/mod.rs
src/ya-comiste-rust/server/src/auth/mod.rs
src/ya-comiste-rust/server/src/graphql_schema.rs

Basically moves all the implementation details under `auth` where it belongs.

YCR: decompose server root mutation

---

src/ya-comiste-rust/server/src/auth/certs.rs

These tests require network so, originally, I was running them separately as kind of integration tests. However, I need to ignore some DB tests which cannot be run on CI (at least not yet since I didn't prepare the infra) and I'd like to run the cert tests sometimes. I might change the strategy later once everything is ready.

YCR: run ignored 'certs' tests on CI

---

src/ya-comiste-rust/Cargo.lock
src/ya-comiste-rust/server/Cargo.toml

I will need them later, but not now.

YCR: remove unused 'rusoto' dependencies

---

.github/dependabot.yml

We are already receiving some errors because of this: https://github.com/adeira/universe/network/updates/86450251
Obviously, the best solution would be to resolve the PRs, however, it's a bit more challenging in a Rust world and, sometimes, it's better to deal with it more slowly.
See: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#open-pull-requests-limit

Dependabot: increase 'open-pull-requests-limit'

---

src/ya-comiste-rust/server/src/warp_graphql/filters.rs
src/ya-comiste-rust/server/src/warp_graphql/handlers.rs
src/ya-comiste-rust/server/src/warp_graphql/models.rs

This helps when user sends some auth value but it's invalid (for example `Bearer: XYZ` instead of `Bearer XYZ`).

YCR: reject unparseable authorization headers

---

src/babel-plugin-transform-sx-tailwind/package.json
src/murmur-hash/CHANGELOG.md
src/murmur-hash/package.json
src/sx/package.json

Release '@adeira/murmur-hash' version 2.0.0

---

.github/dependabot.yml

See: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem

Dependabot: enable Docker package ecosystem

---

scripts/package.json
src/monorepo-npm-publisher/CHANGELOG.md
src/monorepo-npm-publisher/package.json

Release '@adeira/monorepo-npm-publisher' version 2.0.0

---

.github/CODEOWNERS

It's a common situation that @adeira-github-bot cannot approve some PRs completely because they are affecting this global file (because of dependency changes). This PR should fix that.

Codeowners: add @adeira-github-bot for yarn.lock

---

src/ya-comiste-rust/server/src/warp_graphql/handlers.rs

See: https://github.com/rust-lang/rust-clippy/issues/6721 (similar but not identical)
Warp requires to return a `Result` and I don't know how to write it differently to comply with this lint.

YCR: suppress what seems to be a false positive from Clippy

---

src/eslint-config-adeira/__tests__/__snapshots__/index.test.js.snap
src/eslint-config-adeira/__tests__/index.test.js

We are interested only in the differences without any context when diffing stable/strict mode. This makes it much more readable and understandable.

Eslint config: do not show context lines when diffing stable/strict mode

---

src/ya-comiste-rust/server/src/arangodb/mod.rs
src/ya-comiste-rust/server/src/arangodb/pool.rs
src/ya-comiste-rust/server/src/commerce/model/products.rs
src/ya-comiste-rust/server/src/graphql_context.rs
src/ya-comiste-rust/server/src/main.rs
src/ya-comiste-rust/server/src/tests.rs
src/ya-comiste-rust/server/src/warp_graphql/models.rs

The previous DB name was still hardcoded in the recycling logic resulting in inability to recycle => slower app.

YCR: fix DB connection recycling with custom DB name

---

src/eslint-plugin-sx/src/rules/__tests__/fixtures/no-unused-stylesheet/invalid/composability.js
src/sx/README.md
src/sx/src/__tests__/create.test.js
src/sx/src/create.js

Previously, you could select styles conditionally only using the following syntax:
```
styles('button', isDisabled && 'disabled');
styles('button', isDisabled ? 'disabled' : null);
```
Now it's possible to use an object for these conditionals:
```
styles({ button: true, disabled: isDisabled });
```
This is especially useful when all the styles are conditional. For example, imagine a case where you can change the component style with one React property:
```
styles({
primary: props.color === 'primary',
highlight: props.highlight === 'highlight',
});
```

SX: implement conditional object style selector

---

src/sx/index.js

Only type `AllCSSProperties` should be used directly (at least for now) and it's confusing to export some other type which should never be used.

SX remove 'AllCSSPropertyTypes' type export

---

src/sx/index.js
src/sx/src/__tests__/composability.test.js

This allows `false` values in `sx(…)` call similarly to how we allow them in `styles(…)`. Examples of where is this useful:
```
styles('button', isDisabled && 'disabled');
sx(styles.button, isDisabled && props.xstyle);
```

SX: improve DX of conditional composability

---

src/sx-design/index.js
src/sx-design/package.json
src/sx-design/src/Money.js
src/sx-design/src/__tests__/Money.test.js
src/ya-comiste-backoffice/package.json

It does the same as `<Money />` except it can be used in non-React context.

SX Design: expose new 'MoneyFn' function

---

src/ya-comiste-backoffice/src/pos/Checkout.js
src/ya-comiste-backoffice/src/pos/__generated__/CheckoutMutation.graphql.js
src/ya-comiste-rust/schema.graphql
src/ya-comiste-rust/src/commerce/api/mod.rs
src/ya-comiste-rust/src/commerce/model/products.rs
src/ya-comiste-rust/src/pos/api/dal.rs
src/ya-comiste-rust/src/pos/api/mod.rs

Missing pieces:
- accept product keys in GraphQL input and expand them for the DB layer
- send selected product keys and prices from FE

YCR: save selected POS items into DB

---

src/sx-design/package.json
yarn.lock

This dependency is necessary when building the Storybook statically (outside of Universe). So far, we have it only as a peer dependency.

SX Design: add missing '@adeira/sx' dependency

---

src/relay/CHANGELOG.md
src/relay/src/compiler/__tests__/__snapshots__/getSchemaSource.test.js.snap
src/relay/src/compiler/getSchemaSource.js

Before:
- always required signed schema
- always validated the signature
After:
- does not require the schema signature
- verifies the signature only if it exists

Relay: relax compiler schema signature requirements

---

src/sx-design/README.md
src/sx-design/src/Kbd/Kbd.js
src/sx-design/src/Money/Money.js
src/sx-design/src/ProductCard/ProductCard.js
src/sx-design/src/SxDesignProvider.js
src/sx-design/src/SxDesignProviderCSSVariables.js

Basically, the only missing piece was to overwrite the Money component styles via CSS variable.

SX Design: implement dark mode for ProductCard component

---

src/kochka.com.mx/package.json

For some reason there was not used the same version of `flow-bin` as it is in the rest of Universe repo.

Kochka: Flow bin version unification

---

.github/workflows/continuous-integration-bazel.yml

See:
- https://github.com/bazelbuild/bazelisk/releases/tag/v1.7.0
- https://github.com/bazelbuild/bazelisk/releases/tag/v1.7.5

CI: use latest Bazelisk version 1.7.5

---

.github/.kodiak.toml

This could make "automerge priority" label to work alone.
Currently you have to add "automerge" together with "automerge priority".
See https://kodiakhq.com/docs/config-reference#mergeautomerge_label

Kodiak: Improved automerge setup

---

src/sx-design/package.json
yarn.lock

Dependabot sometimes closes the PR prematurely without updating the `package.json` (like in this case: https://github.com/adeira/universe/pull/2107). This PR fixes it.

SX Design: fix '@storybook/addon-actions' dependency version

---

.github/dependabot.yml

This dependency is by nature unstable, and I'd like to always require a specific "master" version instead of the "latest" version (example of incorrect PR: https://github.com/adeira/universe/pull/2117/files).
See: https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#ignore

Dependabot: ignore 'relay-compiler-experimental'

---

src/graphql-global-id/CHANGELOG.md
src/graphql-global-id/package.json

Just a peer dependency upgrade

Graphql Global ID: Release 2.0.1

---

src/sx-design/src/Link/Link.js

The behavior of this rule changed in https://github.com/yannickcr/eslint-plugin-react/pull/2953 and we upgraded the plugin in https://github.com/adeira/universe/pull/2172

Lint: fix `react/jsx-no-target-blank` error

---

src/eslint-config-adeira/TODO.md

I think this is no longer valid.

Eslint config: remove TODO file

---

src/kochka.com.mx/package.json
src/kochka.com.mx/src/Layout.js
src/kochka.com.mx/src/__tests__/Layout.test.js

This change prevents using the `Layout` component with `title` or `subtitle` while `withHiddenTitle` is set because it doesn't make any sense.

KOCHKA: add `Layout` component invariants

---

src/eslint-config-adeira/package.json
src/kochka.com.mx/src/Layout.js
src/sx-design/src/Link/Link.js
yarn.lock

This release includes some fixes for our codebase, see:
- https://github.com/gajus/eslint-plugin-flowtype/pull/477
- https://github.com/gajus/eslint-plugin-flowtype/pull/478

Upgrade `eslint-plugin-flowtype` to the latest version 5.7.1

---

src/kochka.com.mx/src/__tests__/LanguageTag.test.js

This is an attempt to partially revert `LanguageTag` test which was removed in this PR: https://github.com/adeira/universe/pull/2080. I had to disable it because it was miraculously failing on our CI and I was not able to figure out WTF. Let's see if it's better now after some dependency upgrades.

KOCHKA: revert `LanguageTag` test

---

.github/workflows/continuous-integration-javascript.yml
src/example-relay/__github__/.github/workflows/continuous-integration.yml
src/sx-tailwind-website/__github__/.github/workflows/continuous-integration.yml

Note: Node.js version 16 is not required check in our CI yet.
See: https://nodejs.org/en/blog/release/v16.0.0/

CI: enable Node.js 16 tests

---

src/fixtures-tester/src/__tests__/fixtures/simple/folder/note.txt
src/fixtures-tester/src/generateTestsFromFixtures.js

Motivation: When fixture folder contains some another subfolder, it fails on `readFileSync` with `EISDIR: illegal operation on a directory` error.

Fix fixtures-tester to not fail when snapshot folder contains subfolder

---

src/monorepo-shipit/bin/create-patch.js
src/monorepo-shipit/src/Changeset.js
src/monorepo-shipit/src/__tests__/Changeset.test.js
src/monorepo-shipit/src/__tests__/RepoGit.findLastSourceCommit.test.js
src/monorepo-shipit/src/__tests__/ShipitConfig.test.js
src/monorepo-shipit/src/__tests__/__snapshots__/ShipitConfig.test.js.snap
src/monorepo-shipit/src/__tests__/__snapshots__/parsePatchHeader.test.js.snap
src/monorepo-shipit/src/__tests__/fixtures/headers/co-authored-by-multiple.header
src/monorepo-shipit/src/__tests__/fixtures/headers/co-authored-by.header
src/monorepo-shipit/src/filters/__tests__/__snapshots__/moveDirectories.test.js.snap
src/monorepo-shipit/src/filters/__tests__/addTrackingData.test.js
src/monorepo-shipit/src/filters/__tests__/stripDescriptions.test.js
src/monorepo-shipit/src/filters/addTrackingData.js
src/monorepo-shipit/src/parsePatchHeader.js

Basically, we were always printing `adeira-source-id` line as a last one in the commit description. But turned out that `Co-authored-by` lines must be always the last ones for it to work correctly.
This change attempts to do exactly that: it separates the actual description and `Co-authored-by` lines when parsing the commit header (`parsePatchHeader`) and it constructs the commit description correctly in `addTrackingData` function.
Closes: https://github.com/adeira/universe/issues/2261

Shipit: fix `adeira-source-id` position when using `Co-authored-by` lines

---

src/sx-design/.storybook/main.js
src/sx-design/README.md
src/sx-design/package.json
src/sx-design/src/SxDesignProvider.js
yarn.lock

I also changed the wording of README.md a little bit to be more explicit about the inclusivity of this project.
See: https://github.com/storybookjs/storybook/tree/next/addons/a11y

SX Design: install `@storybook/addon-a11y`

---

.eslintignore
.eslintrc.js
src/__flowtests__/lints/__untypedFile.js
src/__flowtests__/lints/unsafe-getters-setters.js
src/__flowtests__/lints/untyped-import.js
src/__flowtests__/lints/untyped-type-import.js
src/eslint-config-adeira/CHANGELOG.md
src/eslint-config-adeira/README.md
src/eslint-config-adeira/__tests__/__snapshots__/index.test.js.snap
src/eslint-config-adeira/ourRules.js
src/example-relay/.eslintrc.js
src/fixtures-tester/src/generateTestsFromFixtures.js
src/monorepo-utils/src/ShellCommand.js
src/monorepo-utils/src/__tests__/ShellCommand.test.js
src/monorepo-utils/src/glob.js
src/sx-tailwind-website/next.config.js
src/sx/scripts/setupTests.js

The purpose of this change is to remove as many things from the global config as possible and move them closer to the actual projects. This plays better with a monorepo approach where every project can have relative freedom to do what it needs/wants to do.

Cleanup global `.eslintrc.js`

---

src/abacus-backoffice/src/constants.js
src/abacus/README.md
src/abacus/kubernetes/README.md
src/abacus/kubernetes/abacus.yaml

This change kinda makes it broken for localhost BUT it makes it work on DigitalOcean (including database backups to S3) which is more important. I will improve the localhost experience later (either via Kustomize or Telepresence or both).

Abacus: make `k8s` ready for DigitalOcean

---

.github/workflows/dockerfile-builder.yml
README.md
src/abacus/Dockerfile
src/abacus/kubernetes/README.md
src/abacus/kubernetes/abacus.yaml

The idea is that `adeira/universe` is responsible for the `Dockerfile` building and pushing so developers do not have to take care of it at all. It uses GitHub Actions build matrix together with `dorny/paths-filter` action to build the Dockerfiles only when needed.

CI: setup Dockerfile builder

---

src/abacus/kubernetes/README.md
src/abacus/kubernetes/third_party/kube-state-metrics/README.md
src/abacus/kubernetes/third_party/kube-state-metrics/cluster-role-binding.yaml
src/abacus/kubernetes/third_party/kube-state-metrics/cluster-role.yaml
src/abacus/kubernetes/third_party/kube-state-metrics/deployment.yaml
src/abacus/kubernetes/third_party/kube-state-metrics/service-account.yaml
src/abacus/kubernetes/third_party/kube-state-metrics/service.yaml

This enables advanced metrics in DigitalOcean.

Abacus: install `kube-state-metrics` (k8s)

---

src/abacus-backoffice/src/constants.js
src/kochka.com.mx/pages/_app.js

I am building the backend so that localhost addresses are not necessary for the local development. So I'd like to change them to remote URL + hide the IP address behind a subdomain (subject to change in the future).

Use temporary Abacus BE URLs

---

.github/dependabot.yml

See: https://github.com/adeira/universe/issues/2341

Dependabot: disable pure ESM packages

---

src/abacus/src/commerce/model/products.rs

It's not needed - added by accident.

Abacus: remove `Product.translation` field

---

package.json

In preparation for native ES modules. We support only Node.js 14+ but specifically because of native ES modules we have to restrict it to Node.js version >=14.13.1.
See: https://nodejs.org/en/blog/release/v14.13.0/

Package.json: add `engines.node`

---

src/babel-plugin-transform-sx-tailwind/package.json
src/babel-preset-adeira/package.json
src/css-colors/package.json
src/eslint-config-adeira/package.json
src/eslint-fixtures-tester/package.json
src/eslint-plugin-adeira/package.json
src/eslint-plugin-sx/package.json
src/fetch/package.json
src/fixtures-tester/package.json
src/flow-config-parser/package.json
src/flow-types-eslint/package.json
src/graphql-bc-checker/package.json
src/graphql-global-id/package.json
src/graphql-relay-fauna/package.json
src/graphql-relay/package.json
src/graphql-resolve-wrapper/package.json
src/js/package.json
src/monorepo-npm-publisher/package.json
src/monorepo-scanner/src/scans/PackageJson.scan.js
src/monorepo-utils/package.json
src/murmur-hash/package.json
src/relay/package.json
src/signed-source/package.json
src/sx-design/package.json
src/sx-jest-snapshot-serializer/package.json
src/sx-tailwind/package.json
src/sx/package.json

See: https://nodejs.org/api/packages.html#packages_determining_module_system
> Package authors should include the "type" field, even in packages where all sources are CommonJS. Being explicit about the type of the package will future-proof the package in case the default type of Node.js ever changes, and it will also make things easier for build tools and loaders to determine how the files in the package should be interpreted.
Related issue: https://github.com/adeira/universe/issues/2341

Explicitly mark all packages with `commonjs` type

---

src/abacus/src/auth/dal/users.rs
src/abacus/src/auth/mod.rs

Also, add a better tracing for this path.

Abacus: fix sessions "write-write" conflict in RocksDB

---

src/abacus-backoffice/package.json
src/kochka.com.mx/package.json
src/sx-design/package.json
src/sx-design/src/ErrorBoundary/ErrorBoundary.js
src/sx-design/src/ErrorBoundary/__tests__/ErrorBoundary.test.js
src/sx-design/translations/source_strings.json

This commit prevents the "The above error..." addendum flowing from React when uncaught error is detected (error boundary catches it). Instead, we simply print the error to console (or call user provided callback `onComponentDidCatch` when available).
See: https://github.com/facebook/react/commit/3938ccc88aa3dcc5a4460474bda40af97dd6e234

SX Design: prevent "The above error..." addendum

---

src/abacus-backoffice/package.json
src/eslint-plugin-sx/package.json
src/example-relay/package.json
src/kochka.com.mx/package.json
src/sx-design/package.json
src/sx-jest-snapshot-serializer/package.json
src/sx-tailwind-website/package.json
src/sx-tailwind/package.json
src/sx/package.json
src/sx/src/__tests__/create.test.js
src/sx/src/create.js

Previously, we didn't allow conditional objects resulting in no styles, for example:
```
styles({ button: false })
```
This change modifies the invariant constraints to allow such situations and return `undefined`.

SX: update conditional object invariants

---

src/monorepo-shipit/src/RepoGit.js
src/monorepo-shipit/src/__tests__/Integration.test.js
src/monorepo-shipit/src/__tests__/__snapshots__/Integration.test.js.snap

I noticed that Dependabot commits are not being exported correctly (see https://github.com/adeira/universe/commit/cc7b3818e06f95c2732f75f165a2b98c6eeab135 vs. https://github.com/adeira/eslint-config-adeira/commit/0948aa9822a603d1001d4911865ac3dfb9bed309). It started happening just a few days ago after Dependabot changed their commit message format.
Turns out that "---" in a description has a special meaning when applying the changes via `git am` (that's what Shipit does internally). Specifically, it removes this part of the messages which removes `adeira-source-id` as well making future Shipit exports broken (Shipit cannot find the `adeira-source-id` handle so it tries to apply the same changes again resulting in a patch conflict).
This change workarounds the issue by prefixing "---" with …

Shipit: fix patch rendering with "---" in description

---

.github/workflows/continuous-integration-rust.yml

Run CI for Rust projects only when there are changed files in the pull request

CI: Rust CI path filter

---

src/sx-design/src/Image/Image.js
src/sx-design/src/ProductCard/ProductCard.js
src/sx-design/src/Skeleton/Skeleton.js
src/sx-design/src/Skeleton/Skeleton.stories.js
src/sx-design/src/Skeleton/__tests__/Skeleton.test.js

Using rounded edges makes it more uniform with the rest of the design system. I also removed `squared` option from `Skeleton` component. It's because this option is not being used and SX Design should implement only what's actually needed and used.

SX Design: use rounded edges (`Image`, `ProductCard`)

---

src/sx-design/.storybook/preview.js
src/sx-design/src/Badge/Badge.js

I also reverted back the default light theme for Storybook - it has issues with triggering the dark mode correctly when it's set by default.

SX Design: use `--sx-radius` in `Badge` component

---

.flowconfig
.flowconfig.template.base
flow-typed/fbt.js
src/relay/src/__flowtests__/mutations.js
src/relay/src/getDataFromRequest.js
src/relay/src/mutations.js
src/relay/src/types.flow.js
src/relay/src/useLazyLoadQuery.js
src/relay/src/useMutation.js

This reverts commit cf0a020d
We are still getting the following error:
```text
Syntax error: Unexpected token, expected "]"
```
Seems like some dependencies are still not updated. Not sure which ones. Will try some time later.

Revert "Flow: use Indexed Access Types"

---

.github/workflows/continuous-integration-javascript.yml

See: https://github.com/actions/setup-node/releases/tag/v2.2.0

CI: enable Yarn dependencies cache

---

.github/workflows/continuous-integration-javascript.yml

This reverts commit 772daf96
Seems like it's not working as expected (https://github.com/adeira/universe/runs/2972556811?check_suite_focus=true#step:3:19).

Revert "CI: enable Yarn dependencies cache"

---

src/monorepo-shipit/bin/importit.js
src/monorepo-shipit/bin/shipit.js
src/monorepo-shipit/package.json
src/monorepo-shipit/src/iterateConfigs.js
yarn.lock

This allows us to filter only a subset of config files when needed. I found this to be a recurring problem when working with Shipit manually.

Shipit: allow specifying glob pattern via CLI

---

src/sx-design/src/Skeleton/Skeleton.js
src/sx-design/src/Skeleton/Skeleton.stories.js
src/sx-design/src/Skeleton/__tests__/Skeleton.test.js

Skeleton component can optionally have a children component in which case the Skeleton tries to measure dimensions of this child and render itself accordingly.

SX Design: allow `children` in `Skeleton`

---

src/css-colors/CHANGELOG.md
src/css-colors/README.md
src/css-colors/package.json
src/css-colors/src/__tests__/calculateContrastRatio.test.js
src/css-colors/src/__tests__/isAccessible.test.js
src/css-colors/src/calculateContrastRatio.js
src/css-colors/src/index.js
src/css-colors/src/isAccessible.js
src/css-colors/src/isBright.js
src/css-colors/src/isDark.js
src/sx-design/.storybook/SxDesignTheme.js
src/sx-design/.storybook/manager.js
src/sx-design/package.json
src/sx-design/src/stories/ColorShowcase.js
src/sx-design/src/stories/Colors.stories.mdx
src/sx-design/src/stories/Introduction.stories.mdx
src/sx/package.json
yarn.lock

The main change in this commit are 2 new functions `calculateContrastRatio` and `isAccessible` (+ deprecation of `isDark` and `isBright`). Function `isAccessible` is better for making decisions about color contrast when it comes to font and background because it takes the actual font and background into account (`isDark` and `isBright` are taking only one color into account completely ignoring the other).
I've shown the use-case in `ColorShowcase` inside SX Design. This commit is a first step towards a new `<Text />` for SX Design. This component should be able to render accessible color based on the background color of its parent.

Colors: add `calculateContrastRatio` and `isAccessible`

---

src/css-colors/CHANGELOG.md
src/css-colors/README.md
src/css-colors/src/__tests__/__snapshots__/convertToRGBTriplet.test.js.snap
src/css-colors/src/__tests__/convertToRGBTriplet.test.js
src/css-colors/src/__tests__/fixtures/validColors.js
src/css-colors/src/__tests__/isColor.test.js
src/css-colors/src/calculateContrastRatio.js
src/css-colors/src/convertToRGBTriplet.js
src/css-colors/src/index.js
src/css-colors/src/isColor.js
src/css-colors/src/utils/__tests__/regexp.test.js
src/css-colors/src/utils/isHSLA.js
src/css-colors/src/utils/isRGBA.js
src/css-colors/src/utils/regexp.js

This commit adds new experimental function `convertToRGBTriplet` that takes any valid CSS/HTML color notation and converts it into RGB triplet that we use for internal calculations of accessibility, brightness and so on.
Use-case: I am building a `Text` component that renders accessible color based on the background. Internally, this component needs to access computed styles (background color) and browsers are returning the color in `rgb(…)` and `rgba(…)` formats (any maybe other formats as well?) and it's challenging to do these conversions in user code.
During the CSS Colors editations I discovered some limitations (most notably the triplet is not a great friend with alpha channel) but I will address these limitations later.

Colors: add new function `convertToRGBTriplet`

---

src/sx-design/README.md
src/sx-design/src/Layout/LayoutBlock.stories.js
src/sx-design/src/Layout/LayoutGrid.js
src/sx-design/src/Layout/LayoutGrid.stories.js
src/sx-design/src/Layout/LayoutInline.stories.js

I first version of a layout component creating a traditional CSS grid.
This is a very common pattern (at least in my apps), so I would like to
extract it and make it available amongst other layout components.
Ideas for the future development is to make it more customizable and
improve responsibility when it comes to mobiles and tablets (basically
change grid and spacing sizes).

SX Design: add new component `LayoutGrid` with a default spacing

---

src/abacus/src/auth/api/mod.rs
src/abacus/src/auth/dal/users.rs
src/abacus/src/auth/mod.rs
src/abacus/src/auth/session.rs

This is so that other people can create an account. Obviously, I still
have to allow them to enter but this is the easiest way how to
"register".

Abacus: automatically register new users

---

src/abacus-backoffice/package.json
yarn.lock

See: https://github.com/vercel/next.js/releases/tag/v11.0.2-canary.22

Abacus BO: use latest `next` version 11.0.2-canary.22

---

src/abacus-backoffice/package.json
yarn.lock

See: https://github.com/vercel/next.js/releases/tag/v11.0.2-canary.23

Abacus BO: use latest `next` version 11.0.2-canary.23

---

.github/workflows/continuous-integration-rust.yml

In the past I changed it in the opposite direction. However, seems like
it's common practice to use `stable` toolchain instead of the hardcoded
version ([1]) as long as it's not for MSRV ([2]).
Moreover, Dependabot cannot keep this version up to date.
[1]: https://github.com/actions-rs/meta/blob/master/recipes/matrix.md
[2]: https://github.com/rust-lang/rfcs/blob/aba44c12231515c380191f2df2eae993a805735f/text/2495-min-rust-version.md

CI Rust: use `stable` toolchain instead of hardcoded version

---

README.md

This change recommends to use `update-suppressions` command that can
both add and remove comments in a single pass.

README: update Flow update instructions

---

src/eslint-config-adeira/README.md
src/eslint-config-adeira/__tests__/__snapshots__/index.test.js.snap
src/eslint-config-adeira/__tests__/__snapshots__/presets.test.js.snap
src/eslint-config-adeira/getCommonConfig.js
src/eslint-config-adeira/ourRules.js
src/eslint-config-adeira/package.json
src/eslint-config-adeira/presetsConfig.js
yarn.lock

It's currently unused (even though the rule should eventually be enabled)
but new rules are coming.
See:
- https://www.npmjs.com/package/eslint-plugin-fb-flow
- https://github.com/facebook/flow/tree/master/packages/eslint-plugin-fb-flow

Eslint config: install new `eslint-plugin-fb-flow`

---

src/abacus-backoffice/package.json
yarn.lock

See: https://github.com/vercel/next.js/releases/tag/v11.0.2-canary.24

Abacus BO: use the latest `next` version 11.0.2-canary.24

---

src/abacus-backoffice/package.json
yarn.lock

See: https://github.com/vercel/next.js/releases/tag/v11.0.2-canary.25

Abacus BO: use the latest `next` version 11.0.2-canary.25

---

src/eslint-config-adeira/__tests__/__snapshots__/presets.test.js.snap
src/eslint-config-adeira/base.js
src/eslint-config-adeira/flowtype.js
src/eslint-config-adeira/index.js
src/eslint-config-adeira/jest.js
src/eslint-config-adeira/next.js
src/eslint-config-adeira/react.js
src/eslint-config-adeira/relay.js
src/eslint-config-adeira/src/EslintConfig.flow.js
src/eslint-config-adeira/src/getCommonConfig.js
src/eslint-config-adeira/src/presets/base.js
src/eslint-config-adeira/strict.js

Previously, we were applying `overrides` settings to every preset even
though it should be applied only to the `base` one (`eslint-comments`
plugin is only part of the `base` preset). This change fixes it.

Eslint config: move overrides where they belong

---

src/example-relay/src/pages/_document.js

We are not using it anymore (SX Design takes care of it).
It was removed here: e6340e9143e9d1ecd992b2204ab40d7e36bb8fc3

Relay example: remove custom font

---

src/abacus-backoffice/package.json
yarn.lock

https://github.com/vercel/next.js/releases/tag/v11.0.2-canary.26

Abacus BO: use the latest `next` version 11.0.2-canary.26

---

src/sx-design/src/Entity/Entity.js
src/sx-design/src/Entity/Entity.stories.js

It's not a responsibility of the `Entity` component to deal with the
layout composition. Instead, users should wrap the `Entity` lines into
`LayoutBlock` and adjust the spacing as needed.

SX Design: remove `Entity` margin block end

---

src/eslint-config-adeira/__tests__/__snapshots__/presets.test.js.snap
src/eslint-config-adeira/__tests__/presets.test.js
src/eslint-config-adeira/index.js
src/eslint-config-adeira/src/EslintConfig.flow.js
src/eslint-config-adeira/src/__tests__/changeNextVersionErrorLevel.test.js
src/eslint-config-adeira/src/changeNextVersionErrorLevel.js
src/eslint-config-adeira/src/detectReactVersion.js
src/eslint-config-adeira/src/getCommonConfig.js
src/eslint-config-adeira/src/presets/base.js
src/eslint-config-adeira/src/presets/react.js
src/eslint-config-adeira/strict.js

Same idea as in cf640a50fe6f2c85ebd2975f0b6d2ce00d1cc1f5
These settings belong to the `base` and `react` preset only and
_I think_ they should be removed from the other presets.

Eslint config: move settings where they belong

---

src/abacus-backoffice/package.json
yarn.lock

https://github.com/vercel/next.js/releases/tag/v11.0.2-canary.27

Abacus BO: use the latest `next` version 11.0.2-canary.27

---

src/abacus-backoffice/package.json
yarn.lock

See:
- https://github.com/vercel/next.js/releases/tag/v11.0.2-canary.28
- https://github.com/vercel/next.js/releases/tag/v11.0.2-canary.29
- https://github.com/vercel/next.js/releases/tag/v11.0.2-canary.30

Abacus BO: use the latest `next` version 11.0.2-canary.30

---

src/sx-design/README.md

It's better to point directly to the component docs because it contains
additional useful information that would be otherwise easy to miss.

SX Design: change Storybook links to docs in README

---

src/example-relay/.babelrc.js

Not sure how this happened. The comment is describing something that is
not happening in the file. It's valid in the OSS version though.

Relay example: remove useless comment

---

src/example-relay/src/pages/ssr.js
src/relay/CHANGELOG.md
src/relay/src/__flowtests__/fetchQuery.js
src/relay/src/index.js

See: https://github.com/facebook/relay/releases/tag/v11.0.0

Relay: use new version of `fetchQuery` from v11

---

src/sx-design/src/Tabs/Tabs.js
src/sx-design/src/Tabs/__tests__/Tabs.test.js

This commit corrects accessibility implementation of the `Tabs`
component. Basically, you can focus the active tab via `Tab` key and
then you can navigate the tabs using arrows (not via `Tab` key).
This implementation should follow recommendations as per: https://www.w3.org/TR/wai-aria-practices/#tabpanel

SX Design: finish `Tabs` accessibility implementation

---

src/eslint-config-adeira/CHANGELOG.md
src/eslint-config-adeira/__tests__/__snapshots__/index.test.js.snap
src/eslint-config-adeira/__tests__/__snapshots__/presets.test.js.snap
src/eslint-config-adeira/src/presets/react.js

From some testing on os x with VoiceOver, it seems the guidance
provided in the rule jsx-a11y/accessible-emoji leads to a degraded
experience with the label not being announced to the user.
See [issue here](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/627)

eslint-config: set jsx-a11y/accessible-emoji to off

---

src/abacus-backoffice/src/pos/ProductsSelected.js
src/abacus-backoffice/translations/source_strings.json
src/sx-design/__flowtests__/Text.js
src/sx-design/src/Text/Text.js

I have a use-case where this makes sense to allow.

SX Design: allow number to be a `Text` children

---

src/abacus-backoffice/src/pos/CheckoutReceipt.js
src/abacus-backoffice/src/pos/recoil/__tests__/selectedItemsState.test.js
src/abacus-backoffice/src/pos/recoil/selectedItemsState.js

I was mixing there several different IDs incorrectly. Specifically, we
have to keep the product IDs unmodified and create additional composite
ID to be able to distinguish various addons selections and correctly
deduplicate them. This fixes the checkout mutation.

Abacus BO: fix selected items state (POS)

---

src/abacus-backoffice/src/pos/ProductsGridModalBody.js
src/sx-design/.npmignore
src/sx-design/__flowtests__/Button.js
src/sx-design/src/Button/Button.js
src/sx-design/src/Text/Text.js

Children should accept `number` nodes as well as iterable of the number
and FBT. I excluded `Icon` from the iterable because we accept icon
only when it's an exclusive children node (see the `Button` logic).

SX Design: improve `Button` children type

---

scripts/package.json
src/abacus-backoffice/package.json
src/abacus-kochka/package.json
src/css-colors/package.json
src/eslint-fixtures-tester/package.json
src/example-relay/package.json
src/fetch/package.json
src/fixtures-tester/package.json
src/flow-config-parser/package.json
src/graphql-global-id/package.json
src/graphql-relay-fauna/package.json
src/icons/package.json
src/js/CHANGELOG.md
src/js/package.json
src/monorepo-scanner/package.json
src/monorepo-shipit/package.json
src/monorepo-utils/package.json
src/relay/package.json
src/sx-design/package.json
src/sx-tailwind/package.json
src/sx/package.json

Full diff:
```diff
diff --git a/src/js/.npmignore b/src/js/.npmignore
index 1d2c8b25f..c912533dd 100644
--- a/src/js/.npmignore
+++ b/src/js/.npmignore
@@ -1,3 +1 @@
__tests__
-BUILD.bazel
-BUILD
diff --git a/src/js/BUILD.bazel b/src/js/BUILD.bazel
deleted file mode 100644
index 3e2c4c16f..000000000
--- a/src/js/BUILD.bazel
+++ /dev/null
@@ -1,11 +0,0 @@
-load("//:bazel/macros/build_yarn_workspace.bzl", "build_yarn_workspace")
-load("//:bazel/macros/test_yarn_workspace.bzl", "test_yarn_workspace")
-
-build_yarn_workspace(
-    name = "js",
-    package_name = "@adeira/js",
-)
-
-test_yarn_workspace(
-    name = "test",
-)
diff --git a/src/js/CHANGELOG.md b/src/js/CHANGELOG.md
index 9d43dacf4..30d885a13 100644
--- a/src/js/CHANGELOG.md
+++ b/src/js/CHANGELOG.md
@@ -1,5 +1,12 @@
+# 2.1.1
+ …
```

JS: release version 2.1.1

---

package.json
src/eslint-config-adeira/package.json
src/eslint-plugin-adeira/package.json
src/eslint-plugin-adeira/src/rules/__tests__/no-duplicate-import-type-import.test.js
src/eslint-plugin-adeira/src/rules/no-duplicate-import-type-import.js
src/flow-types-eslint/src/types/ImportDeclaration.js

I decided to ignore side-effect imports completely because it felt
strange to be enforcing consolidation of side-effects and type imports.
Closes: https://github.com/adeira/universe/issues/3410

Eslint plugin: fix `no-duplicate-import` rule for side-effect imports

---

.github/workflows/continuous-integration-javascript.yml

See: https://nodejs.org/en/blog/release/v17.0.0/
TODO:

CI: use Node.js version 17

---

src/sx-design/src/Money/Money.js

Something changed between Node.js 17.1 and 17.2 and our previous
implementation stopped working. Regardless of this fact, it seems like
we should've used numbering system `latn` in a first place.
This commit fixes the issue and unblocks all pending pull requests.

SX Design: fix `Money` and `MoneyFn` rendering

---

.github/dependabot.yml

It's a pure ESM package, see: https://github.com/adeira/universe/issues/2341

Dependabot: disable `chalk` dependency

---

.github/workflows/continuous-integration-javascript.yml

This makes sure that our generated files are always up-to-date. This
check works for the whole monorepo regardless of the projects inside
(all Relay projects will be checked).

CI: run Relay check

---

src/sx-design/__flowtests__/LinkButton.js
src/sx-design/src/Link/LinkButton.js

Also, add some basic Flow tests for `LinkButton`.

SX Design: allow `Money` component as a `LinkButton` children

---

src/js/.npmignore
src/js/__flowtests__/invariant.js

`invariant` has a special place in a Flow ecosystem and the type
behavior of this function can be a bit surprising. I wanted to capture
this nature by adding some explicit Flow tests showing this behavior.

JS: add `invariant` Flow tests

---

src/abacus/kubernetes/README.md
src/abacus/kubernetes/abacus.yaml

> If startingDeadlineSeconds is set to a large value or left unset (the default) and if concurrencyPolicy is set to Allow, the jobs will always run at least once.
See: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#cron-job-limitations

Abacus: set DB backup `concurrencyPolicy` to `Allow`

---

src/abacus/server/src/menu/mod.rs

And remove pending coffee as it is not really a product we want to have there (but we still offer it in person).

Abacus: add Flat white to our menu

---

.github/dependabot.yml

Most of the deps are now handled by Renovate, and it seems to be working well.

Cleanup Dependabot config

---

src/x/src/main.rs

This way we can run `./x t --watch` instead of `./x t -- --watch`

X: allow hyphen values

---

.yarnrc.yml

We are receiving many dependency upgrades and this can get very annoying. Let's skip these files for now even though it might be important for the releases.

Yarn add `package.json` and `yarn.lock` into `changesetIgnorePatterns`

---

src/abacus/server/src/menu/mod.rs

We are replacing and improving our tea options so there are going to be more changes to this section soon.

Abacus: remove "Maison de Cannelle" from the menu

---

.github/workflows/continuous-integration-javascript.yml
.github/workflows/continuous-integration-rust.yml
.github/workflows/playwright.yml
src/sx-design/package.json
src/sx-design/playwright.config.js
src/sx-design/tests/.eslintrc.js
src/sx-design/tests/README.md
src/sx-design/tests/ui/homepage.play.js
yarn.lock

Just to make sure it still works after updating Storybook dependencies as it gets broken _very_ often.

SX Design: test Storybook via Playwright

---

.github/workflows/daily-rust-cargo-update.yml

See: https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

CI: add `workflow_dispatch` event to the daily Rust Cargo workflow

---

.github/workflows/daily-rust-cargo-update.yml

It doesn't make any sense to use `paths-filter` in this scenario. The affected projects are defined by `matrix.manifest`.

CI: fix Rust Cargo daily workflow

---

.github/workflows/continuous-integration-rust.yml

MacOS is still relevant, but we never had a problem with it, and it will simplify the CI pipeline significantly.

CI: remove `macos-latest` from Rust OS

---

src/abacus-docs/package.json
src/abacus-docs/pages/docs/security.md
yarn.lock

This seems to be one of the required `@babel/preset-flow` peer dependencies.

Abacus docs: install `@babel/core`

---

src/abacus-backoffice/package.json
src/abacus-kochka/package.json
src/example-relay/package.json
src/relay/bin/compiler.js
src/relay/package.json
yarn.lock

Yarn Berry doesn't allow accessing bins from nested dependencies, so we have to expose our own binary (wrapping the original one).

Relay: expose experimental `compiler` bin wrapper

---

src/abacus/schema.graphql
src/abacus/server/src/cats/dal.rs

Related issue: https://github.com/adeira/universe/issues/4520

Abacus: make `CatInfo` description optional

---

src/abacus/server/src/main.rs

See: https://rust-lang.github.io/rust-clippy/master/index.html#missing_panics_doc

Abacus: forbid `clippy::missing_panics_doc`

---

package.json
src/eslint-config-adeira/CHANGELOG.md
src/eslint-config-adeira/package.json
yarn.lock

Most likely the last 7.x version before releasing `hermes-eslint` version (major).

Eslint config: release version 7.7.0

---

src/abacus-backoffice/package.json
src/abacus-kochka/package.json
src/forms/package.json
src/relay/CHANGELOG.md
src/relay/package.json
yarn.lock

Includes Relay 14.1.0, see: https://github.com/facebook/relay/releases/tag/v14.1.0

Relay: release version 6.2.0

---

src/monorepo-shipit/src/__tests__/RepoGit.findFirstAvailableCommit.test.js
src/monorepo-shipit/src/__tests__/RepoGit.findLastSourceCommit.test.js
src/monorepo-shipit/src/__tests__/parsePatch.test.js
src/monorepo-shipit/src/filters/moveDirectories.js

Flow: codemod `src/monorepo-shipit` (`annotate-lti-experimental`)

---

src/abacus-kubernetes/abacus/arangodb.yaml
src/abacus-kubernetes/manual-arangodb-restore.yaml

See: https://github.com/arangodb/arangodb/blob/v3.9.3/CHANGELOG

Abacus: use the latest `arangodb/arangodb:3.9.3`

---

src/abacus/server/src/stripe/fixtures/payment_intent.requires_action.json
src/abacus/server/src/stripe/tests.rs
src/abacus/server/src/stripe/webhook.rs

This also adds some other missing `payment_intent.*` Stripe events.

Abacus: fix `payment_intent.requires_action` Stripe event parsing

---

src/sx-design/package.json
yarn.lock

It seems to be currently broken (and 2.0.2 doesn't seem to be working either), see: https://github.com/woltapp/blurhash/issues/202

SX Design: temporarily revert `blurhash` dependency update

---

.github/workflows/continuous-integration-javascript.yml

See: https://nodejs.org/en/blog/announcements/v19-release-announce/
TODO:

CI: enable Node.js version 19

---

src/monorepo-npm-publisher/src/__tests__/collectFilenames.test.js
src/monorepo-npm-publisher/src/collectFilenames.js
src/monorepo-npm-publisher/src/index.js

This is mostly to make sure that our future dependency upgrades won't break this package.

NPM Publisher: add `collectFilenames` test

---

src/sx-design/package.json
src/sx-design/src/DateTime/__tests__/DateTime.test.js
src/sx-design/src/Money/__tests__/Money.test.js
yarn.lock

Apparently, it's possible to have Node.js 19.1.0 with older ICU version. So we should really be focusing on the ICU version itself, not Node.js version.
I removed `semver` dependency because it doesn't support X.Y version schemas. Simple number comparison should do in this case.

SX Design: improve ICU 72.1 detection

---

x

See: https://www.shellcheck.net/wiki/SC2312
Fixes the following error:
```
In ./x line 45:
curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- -y
^-- SC2312 (info): Consider invoking this command separately to avoid masking its return value (or use '|| true' to ignore).
```

Shellcheck: disable SC2312

---

.github/renovate.json5

It doesn't work correctly: it waits for opening the PR 3 days, but then it can update Yarn lock file with a newly released patch version that is much younger (and this version could be yanked anytime).

Renovate: remove `npm:unpublishSafe` preset

---

.eslintrc.js
src/__flowtests__/ReactElement.js
src/abacus-backoffice/pages/index.js
src/abacus-kochka/pages/_document.js
src/eslint-config-adeira/__tests__/__fixtures__/valid-eslint-examples/react/no-unused-state.js
src/eslint-config-adeira/__tests__/index.test.js
src/eslint-plugin-adeira/src/index.js
src/eslint-plugin-adeira/src/rules/__tests__/sort-imports.test.js
src/eslint-plugin-adeira/src/rules/sort-imports.js
src/forms/src/FormMultiSelect.js
src/forms/src/FormSelect.js
src/forms/src/private/BaseSelect.js
src/monorepo-shipit/src/phases/createImportSyncPhase.js
src/monorepo-shipit/src/phases/createSyncPhase.js
src/relay/src/__flowtests__/Environment.js
src/sx-design/__flowtests__/Button.js
src/sx-design/__flowtests__/Entity.js
src/sx-design/__flowtests__/LinkButton.js
src/sx-design/__flowtests__/Text.js
src/sx-design/src/Entity/EntityField.js
src/sx-design/src/Loader/Loader.js
src/sx-design/src/SxDesignPortal.js
src/sx-design/src/Text/Text.js

Not yet enabled for the public. This new rule is basically a fork of the official `sort-imports` but without any additional features and tailored specifically for Adeira needs.
It currently supports only type imports. Support for additional imports will be added later once decided how to.

Eslint plugin: add new `sort-imports` rule

---

.github/workflows/continuous-integration-javascript.yml
.github/workflows/npm-publisher.yml

From now on this repository should support LTS and Current Node.js versions only. See: https://nodejs.org/en/download/

CI: drop Node.js 16.x

---

src/abacus/Cargo.lock
src/abacus/server/Cargo.toml

Related issue: https://github.com/graphql-rust/juniper/issues/1142
Changelog: https://github.com/graphql-rust/juniper/compare/juniper-v0.15.10...juniper-v0.15.11

Abacus: use Juniper version 0.15.11

---

.github/renovate.json5

This approach is not compatible with the new GitHub merge queue I am currently testing.

Renovate: do not automerge dev dependencies

---

.github/workflows/continuous-integration-javascript.yml
.github/workflows/continuous-integration-rust.yml
.github/workflows/playwright.yml
.github/workflows/shellcheck.yml

Seems like `pull_request` and `push` and duplicate in this context and create twice as CI runs as needed. We should probably use one or the other.

Partially revert 2c9f9f683d21e53e95e914a9edaebb07b4afa6ba

---

.github/renovate.json5

This reverts commit 7d7b232552bb0f2d7bb2f7fa4c62c5ef764501fb.
Seems like it doesn't work (maybe because the changelog is in `rst` format?)

Revert "Renovate: set custom changelog URL for `amazon/aws-cli`"

---

.github/workflows/weekly-browserslist-update.yml

CI is currently failing because of outdated `browserslist` (`caniuse-lite`) dependency. This should prevent such issues. See: https://github.com/adeira/universe/actions/runs/4401547429/jobs/7707849388

CI: create new "Weekly Browserslist update" job

---

.github/workflows/playwright.yml
src/sx-design/package.json

Annoyingly, there is currently an issue with Storybook (see: https://github.com/storybookjs/storybook/issues/16555). We already have to do this in CI to make Playwright work, and it also affects Vercel deployments (and builds on Node.js 18).

SX Design: patch `build-storybook` script

---

.github/workflows/continuous-integration-javascript.yml
.github/workflows/continuous-integration-rust.yml
.github/workflows/playwright.yml
.github/workflows/shellcheck.yml

Replaces generic `push` event with more appropriate `pull_request` event.
See: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
Note: previously, there was an issue with the CI jobs running twice (see: https://github.com/adeira/universe/commit/ccf3dec7e98acc5c994280c07dc14ba26dabd9c3). This change should fix it.
Closes: https://github.com/adeira/universe/issues/6110

CI: run checks for 3rd party contributions

---

src/monorepo-shipit/src/RepoGit.js
src/monorepo-utils/src/Git.js
src/shell-command/index.js
src/shell-command/src/ShellCommand.js
src/shell-command/src/__tests__/ShellCommand.test.js

This change started with investigating why `src/monorepo-shipit/src/__tests__/RepoGit.findLastSourceCommit.test.js` fails on some machines. Here is an example of such failure:
```
● can find last source commit
expect(received).toBe(expected) // Object.is equality
Expected: "636abcdef012345840"
Received: null
27 |   const description = addTrackingData(new Changeset().withID(fakeCommitID)).getDescription();
28 |   const repo = createGITRepoWithCommit(description);
> 29 |   expect(repo.findLastSourceCommit(new Set())).toBe(fakeCommitID);
|                                                ^
30 | });
31 |
32 | it('can find last source commit with Co-authored-by', () => {
at Object.toBe (src/__tests__/RepoGit.findLastSourceCommit.test.js:29:48)
```
Interestingly, this doesn't happen on CI. It …

Shipit: correctly propagate PATH to `ShellCommand`

---

scripts/publishedPackages.json
src/monorepo-shipit/package.json
src/monorepo-utils/package.json
src/shell-command/.npmignore
src/shell-command/LICENSE
src/shell-command/package.json
yarn.lock

This will be necessary in order to successfully publish Shipit (see: https://github.com/adeira/universe/pull/6109)

Publish a new package `@adeira/shell-command` to NPM

---

.github/workflows/shipit.yml
scripts/publishedPackages.json
src/monorepo-shipit/.npmignore
src/monorepo-shipit/README.md
src/monorepo-shipit/bin/importit.js
src/monorepo-shipit/bin/shipit.js
src/monorepo-shipit/package.json
src/monorepo-shipit/src/RepoGit.js
src/monorepo-shipit/src/RepoGitFake.js
src/monorepo-shipit/src/accounts.js
src/monorepo-shipit/src/iterateConfigs.js
yarn.lock

This pull request updates monorepo-shipit to be able to be published to NPM and used by anyone. It:
- introduces new command line args
- removes hardcoded accounts
- updates internal workflow runs to use the new args
There is an opportunity in a follow up to replace the command line library with something like commanderjs so there is an easier way to look for available args, etc.
Related to #6096. Need to test it end-to-end before closing the issue.

Publish monorepo-shipit

---

src/monorepo-shipit/src/RepoGit.js
src/monorepo-shipit/src/RepoGitFake.js
src/monorepo-shipit/src/__tests__/RepoGit.commitPatch.test.js
src/monorepo-shipit/src/__tests__/RepoGit.findLastSourceCommit.test.js
src/monorepo-shipit/src/phases/createSyncPhase.js
src/monorepo-shipit/src/phases/createVerifyRepoPhase.js

This pull request:
- fixes hardcoded branches during the shipit verify step
- includes the first revision commit when running in a new repo
- adds `--committer-date-is-author-date` to `git am` call in `commitPatch` to ensure each commit uses the author datetime, preventing the initial sync forcing every commit to have the same commit timestamp 
With these changes (applied as a patch) I've been able to sync a repo in CI successfully.

Fixes some edge cases in monorepo-shipit

---

src/monorepo-shipit/ConfigType.flow.js
src/monorepo-shipit/README.md
src/monorepo-shipit/src/Changeset.js
src/monorepo-shipit/src/ShipitConfig.js
src/monorepo-shipit/src/__tests__/Changeset.test.js
src/monorepo-shipit/src/__tests__/ShipitConfig.test.js
src/monorepo-shipit/src/__tests__/__snapshots__/Integration.test.js.snap
src/monorepo-shipit/src/__tests__/__snapshots__/ShipitConfig.test.js.snap
src/monorepo-shipit/src/filters/__tests__/__snapshots__/moveDirectories.test.js.snap
src/monorepo-shipit/src/filters/__tests__/addTrackingData.test.js
src/monorepo-shipit/src/filters/__tests__/stripDescriptions.test.js
src/monorepo-shipit/src/iterateConfigs.js

This pull request:
- adds the `transformCommitMessage` option to shipit config so consumers can optionally transform their commit messages, such as removing github issues and pull requests from messages
For context currently when running ShipIt it doesn't do anything with commit messages. This is a problem when it exposes internal issues & pull requests that don't exist in the public repo! So, hence this feature add. I can remove them on my end.

feat: adds commit message transformer to shipit

---

src/monorepo-shipit/bin/importit.js
src/monorepo-shipit/bin/shipit.js
src/monorepo-shipit/package.json
yarn.lock

The previous solution was good enough when the tool was used internally but now I see the need to have a better CLI interface. This not only provides better out-of-the box validations but also supports `--help` option.
I've also improved the Importit interface to support `--pull-request` option (instead of repo URL and PR number). I believe it's more natural to just copy the PR URL and use it.

Shipit: improve CLI interface

---

src/rossum-hooks/src/sync-queues/index.js
src/rossum-hooks/src/utils/fetchRossumAPI.js

The purpose is to mimic `fetch` API instead of using `https` module from Node.js directly (which doesn't have such friendly interface).
This change also includes `sync-queues` hook migration to use this new function.

Rossum hooks: add new `fetchRossumAPI` function

---

.github/renovate.json5

Just a test to see whether this setting would work together with merge queues and whether it would reduce the load on our CI.

Renovate: use rebase when conflicted

---

src/abacus-tools/pages/_app.css

This is to make the loading as fast as possible. No need for custom font.

Abacus Tools ext: replace `Inter` font with `Arial`

---

src/abacus-tools/src/components/Jumbo.js

This is to prevent the time font horizontal jumping.

Abacus Tools ext: use `font-variant-numeric: tabular-nums`

---

.github/workflows/continuous-integration-javascript.yml

See: https://github.com/nodejs/Release

CI: drop support for Node.js 19

---

src/homebrew-universe/Formula/rossum-dmv2-analyze.rb
src/homebrew-universe/README.md

It's most likely broken, just an init commit.

Homebrew: add `rossum-dmv2-analyze` formula

---

.github/workflows/continuous-integration-rust.yml

The purpose of this job is to wait for the completion of the `rust-test` jobs (matrix) and evaluate whether the run was successful or not. This is useful when configuring the required jobs in GitHub UI (we can require just this one job instead of all the jobs in the test matrix).

CI: add new `rust-test-results` job

---

.github/workflows/playwright.yml

The purpose of this job is to wait for the completion of the `playwright-test` jobs (matrix) and evaluate whether the run was successful or not. This is useful when configuring the required jobs in GitHub UI (we can require just this one job instead of all the jobs in the test matrix).

CI: add new `playwright-test-results` job

---

src/rossum-sa-extension/manifest.json
src/rossum-sa-extension/package.json
src/rossum-sa-extension/popup/popup.html
src/rossum-sa-extension/scripts/annotation-schema-ids.js

This fixes some internal errors popping up (especially on the `/statistics` page).

Rossum SA ext: correctly refine observed nodes

---

src/flow-config-parser/src/utils.js
src/js/src/isNumeric.js
src/js/src/isObjectEmpty.js
src/monorepo-scanner/src/isValidLicense.js
src/monorepo-utils/src/glob.js
src/relay/src/internal/helpers.js

See: https://flow.org/en/docs/types/type-guards/

Flow: cleanup deprecated predicates `%checks`

---

src/babel-preset-adeira/CHANGELOG.md
src/babel-preset-adeira/package.json
src/babel-preset-adeira/src/__tests__/__fixtures__/features/throw-expressions.js
src/babel-preset-adeira/src/__tests__/__snapshots__/configs.test.js.snap
src/babel-preset-adeira/src/__tests__/__snapshots__/transformations.test.js.snap
src/babel-preset-adeira/src/index.js
yarn.lock

See: https://github.com/tc39/proposal-throw-expressions

Babel preset: remove experimental support for throw expressions

---

src/eslint-plugin-sx/src/rules/__tests__/__snapshots__/no-unused-stylesheet.test.js.snap
src/eslint-plugin-sx/src/rules/__tests__/no-unused-stylesheet.test.js
src/fixtures-tester/src/__tests__/__snapshots__/generateTestsFromFixtures.test.js.snap
src/fixtures-tester/src/generateTestsFromFixtures.js
src/flow-config-parser/src/__tests__/__snapshots__/parse.test.js.snap
src/monorepo-shipit/src/__tests__/__snapshots__/parsePatch.test.js.snap
src/monorepo-shipit/src/__tests__/__snapshots__/parsePatchHeader.test.js.snap
src/sx-design/src/ErrorBoundary/__tests__/ErrorBoundary.test.js
src/sx-design/src/Link/__tests__/Link.test.js
src/sx-design/src/Modal/__tests__/Modal.test.js
src/sx/src/__tests__/keyframes.test.js
src/x/src/executors/tests.rs

This arg helps to uncover some leaky tests which I've fixed. It was also necessary to change the logic of some test generators and their snapshots to be stable with `--randomize` (by generating test hash instead of relying just on the snapshot name and ordering).

Jest: run tests with `--randomize`

---

.github/workflows/dockerfile-builder.yml

Dockerfile builder: remove `abacus-docs`

---

src/sx-design/.storybook/main.js
src/sx-design/package.json
yarn.lock

Unused and, moreover, it blocks `@testing-library/dom` upgrade.

SX Design: remove unused Storybook dependency

---

.github/workflows/continuous-integration-javascript.yml

See: https://nodejs.org/en/blog/release/v22.0.0

CI: add Node.js 22
